export const customerJourneys = [
 {id:"carriers",label:"Trucking companies",short:"Fleet & driver operations",title:"Run the company. Not just the next load.",intro:"For fleet owners and operations managers coordinating their own customers, trucks, drivers and back office.",question:"Where are the trucks—and what needs to happen next?",focus:["Fleet visibility","Load planning","Driver reconciliation"],steps:[{title:"Plan the work",body:"Bring customer orders and configured EDI tenders into load planning. Review vehicles, stops and capacity before assigning the truck and driver."},{title:"Follow the fleet",body:"Use ELD-fed map positions and reporting freshness to understand where equipment is and which movements need attention."},{title:"Close the books",body:"Carry delivery records into invoicing, driver pay review, expenses and settlement reconciliation."}],demo:"Bring your fleet size, ELD provider, driver pay process and OEM connection requirements.",link:"/solutions/carriers",view:"carrier"},
 {id:"brokers",label:"Brokerages",short:"Customers, carriers & margin",title:"Keep the customer promise connected to the load.",intro:"For brokerage teams managing customer relationships, carrier coverage and the economics of every vehicle movement.",question:"Which loads need coverage, follow-up or a financial decision?",focus:["Order coordination","Carrier coverage","Billing & receivables"],steps:[{title:"Win and organize the work",body:"Keep customer details, quotes and orders together so the dispatch team can see what was agreed."},{title:"Coordinate the movement",body:"Review carrier fit, assign the work and follow shipment milestones and delivery records."},{title:"Review the economics",body:"Connect customer billing, carrier payables and operational reporting to the order behind the numbers."}],demo:"Bring a recurring lane, your carrier selection process and an example of the billing handoff.",link:"/solutions/brokers",view:"broker"},
 {id:"dealers",label:"Dealerships",short:"Vehicle requests & delivery",title:"Know what is arriving. Keep the lot informed.",intro:"For dealership teams requesting transport and following vehicles between auctions, stores and customer locations.",question:"What is the status of the vehicles we are waiting on?",focus:["Transport requests","VIN status","Delivery records"],steps:[{title:"Request the movement",body:"Put the vehicle, pickup location and destination into a transport request with the details the operations team needs."},{title:"Follow the vehicle",body:"Review the shipment status shared through your portal and keep your team informed as the order progresses."},{title:"Receive the record",body:"Find available delivery documents and invoice information without rebuilding the shipment history from messages."}],demo:"Bring an auction pickup or store transfer and the status information your team needs before arrival.",link:"/solutions/dealers",view:"orders"},
 {id:"wholesale",label:"Auctions & wholesale",short:"Vehicle lists & lot handoffs",title:"Move the vehicle list into a working plan.",intro:"For wholesale and auction operations coordinating multiple vehicles, pickup locations, release requirements and receiving teams.",question:"Which vehicles are ready to move—and where does each one belong?",focus:["Vehicle intake","Pickup coordination","VIN-level records"],steps:[{title:"Organize the intake",body:"Bring vehicle lists and pickup details into a consistent order process. Review supported file formats and mapping during setup."},{title:"Coordinate the handoff",body:"Keep release readiness, pickup locations and carrier assignments attached to the work."},{title:"Follow each unit",body:"Track order status and available condition and delivery records at vehicle level as units move toward their destinations."}],demo:"Bring a typical vehicle-list export, pickup requirements and your receiving-location workflow.",link:"/solutions/wholesale",view:"orders"}
] as const;
export const customerQuestions = [
 ["Is Prevayl a load board or a full TMS?","Prevayl includes a load board within a broader operating platform. Trucking companies can use carrier workflows for dispatch, fleet and drivers, ELD visibility, accounting and reconciliation. Brokers, dealers and wholesale teams have different workflows and access."],
 ["Can we keep our existing customers and lanes?","The demo can focus on the business you already run: direct customer work, brokered loads, recurring lanes and vehicle movements. Bring examples so the team can show the relevant workflow."],
 ["How do ELD and OEM connections fit in?","Supported ELD connections provide data for fleet visibility. EDI and VTIMS workflows depend on the partner, transaction mapping, credentials and acceptance requirements. Review your specific providers and OEM requirements during setup."],
 ["Can we bring our existing data?","Discuss customers, carriers, vehicles and shipment history with the onboarding team. The import scope depends on your source files, field mapping and data quality; agree what to migrate and how it will be checked."],
 ["What does onboarding involve?","Start with the roles, workflows and records your team needs. Then confirm data imports, integrations, permissions and training before agreeing a rollout plan. Timing depends on the scope of your operation."],
 ["How are pricing and account terms determined?","Sales will review your business type, team, vehicle volume, modules and integration needs. Confirm pricing, onboarding scope and contract terms in your proposal."]
] as const;
