"use client";
import {useState} from "react";
import Link from "next/link";
const seats=[
{label:"Brokers",title:"Connect the people. Own the movement.",body:"Coordinate the customer, carrier and economics of every order.",href:"/solutions/brokers",steps:["Customer request","Carrier selection","Order economics"],detail:["Quote the lane","Review the carrier fit","Follow receivables and payables"],kind:"broker"},
{label:"Carriers",title:"Keep the truck and the work together.",body:"Connect the driver, vehicle positions and delivery work.",href:"/solutions/carriers",steps:["Load planning","Driver handoff","Delivery evidence"],detail:["Review available positions","Share pickup context","Keep the eBOL with the load"],kind:"carrier"},
{label:"Dealers",title:"See where your vehicles stand.",body:"Follow vehicle movements without another status call.",href:"/solutions/dealers",steps:["Request a move","Track the vehicle","Receive the record"],detail:["Submit pickup and destination","Read the shipment status","Find the delivery documents"],kind:"dealer"},
{label:"Auctions & wholesale",title:"From purchased to on the way.",body:"Keep purchased vehicles moving toward the receiving lot.",href:"/solutions/wholesale",steps:["Purchased vehicles","Release readiness","Receiving lot"],detail:["Bring the vehicle list together","Coordinate pickup details","Follow the movement to delivery"],kind:"auction"}
];
export function AudienceLane(){const [active,setActive]=useState(0);const seat=seats[active];return <section className="pvl-section pvl-wrap" id="everyone-in-the-lane"><div className="pvl-section-heading"><div><p className="pvl-eyebrow">Built for your seat at the table</p><h2>Everyone in the lane.</h2></div><p>Different responsibilities. A shared view of the movement.</p></div><div className="lane-experience"><div className="lane-panorama"><img src="/illustrations/lane-ecosystem.webp" width="1536" height="1024" alt="Illustrated auto transport ecosystem connecting a broker office, carrier staging area, dealership and auction lot" loading="lazy"/><span className="lane-art-label">ONE CONNECTED OPERATION · ILLUSTRATION</span><div className="lane-stations" aria-hidden="true">{seats.map((s,i)=><span key={s.label} className={i===active?"active":""}><b>0{i+1}</b>{s.label}</span>)}</div></div><div className="lane-tabs" role="group" aria-label="Explore your role">{seats.map((s,i)=><button key={s.label} aria-pressed={active===i} onClick={()=>setActive(i)}><span>0{i+1}</span>{s.label}<b>↗</b></button>)}</div><div className="lane-detail" aria-live="polite"><div><p className="pvl-eyebrow">{seat.label}</p><h3>{seat.title}</h3><p>{seat.body}</p><Link className="pvl-text-link" href={seat.href}>Explore {seat.label.toLowerCase()} →</Link></div><div className={"lane-workflow lane-"+seat.kind}><span className="lane-example">WORKFLOW EXAMPLE</span>{seat.steps.map((s,i)=><div key={s}><span className="lane-stage">0{i+1}</span><section><strong>{s}</strong><small>{seat.detail[i]}</small></section><b>{i===2?"✓":"↓"}</b></div>)}</div></div></div><div className="lane-explore"><Link href="/platform">Explore the platform <span>See the workspaces →</span></Link><Link href="/pricing">Find your fit <span>Plans for your operation →</span></Link></div></section>}
