"use client";
import { useState } from "react";
import Link from "next/link";
import {BotVisual,VisualIcon} from "./VisualExamples";
const bots=[
 {id:"margin",glyph:"↗",name:"Margin Guard",tag:"Protect the economics",headline:"See the margin before the load moves.",body:"Compare the customer price with carrier cost and surface the loads that deserve a closer look. Keep your team focused on exceptions.",trigger:"A priced order is evaluated",work:"Calculate margin and compare the threshold",result:"Surface an exception for review",labels:["Customer price","Carrier cost","Gross margin"],values:["$1,250","$1,150","$100 · 8%"],notice:"Margin is below the example 10% threshold.",detail:"Review the rate before moving this order forward.",history:["Order pricing received","Margin calculated at 8%","Exception added to the review queue"],control:"Margin thresholds"},
 {id:"match",glyph:"⇄",name:"Carrier Match",tag:"Find the right fit",headline:"Give your dispatcher a focused shortlist.",body:"Bring lane fit, carrier history and your matching criteria into the same decision. Review the recommendation alongside the order.",trigger:"A load needs a carrier",work:"Compare lane fit and matching criteria",result:"Review the suggested carrier",labels:["Origin","Destination","Equipment"],values:["Detroit, MI","Nashville, TN","Open transport"],notice:"A carrier matches the example lane criteria.",detail:"Review the carrier’s details and documents before assignment.",history:["Lane criteria received","Matching carriers compared","Recommendation ready"],control:"Lane and carrier criteria"},
 {id:"price",glyph:"$",name:"Pricer",tag:"Build a better quote",headline:"Put the lane history beside the number.",body:"Use the pricing workspace to evaluate a lane with the evidence available. A thin-history lane deserves a different decision from one you run every week.",trigger:"A lane needs a price",work:"Evaluate available lane history",result:"Review the recommendation and confidence",labels:["Example lane","Vehicle","History"],values:["MI → TN","Sedan","Limited"],notice:"This example lane needs closer review.",detail:"Validate the recommendation against current carrier availability.",history:["Lane and vehicle received","Available history evaluated","Pricing context prepared"],control:"Pricing inputs"},
 {id:"status",glyph:"◎",name:"Status Bot",tag:"Keep customers informed",headline:"Turn a milestone into a useful update.",body:"Connect operational events with customer communication. Configure the channels and events that matter to your operation.",trigger:"An order reaches a configured milestone",work:"Prepare the customer update",result:"Send through the enabled channel",labels:["Milestone","Channel","Order"],values:["Picked up","Email","DEMO-1042"],notice:"A pickup update is prepared in this example.",detail:"The message follows the order’s event and communication settings.",history:["Pickup milestone received","Customer update prepared","Example message displayed"],control:"Events and communication channels"},
 {id:"return",glyph:"↻",name:"Reengagement",tag:"Reconnect with carriers",headline:"Put a familiar lane back in front of a carrier.",body:"Identify inactive carrier relationships and use relevant lane context for outreach. Apply your cooldown rules to keep follow-up useful.",trigger:"A carrier meets inactivity criteria",work:"Check recent contact and lane relevance",result:"Prepare eligible outreach",labels:["Inactivity","Recent contact","Lane fit"],values:["35 days","None in 7 days","MI → TN"],notice:"The example carrier is eligible for follow-up.",detail:"Review the outreach configuration before enabling automated sends.",history:["Inactivity criteria evaluated","Contact cooldown checked","Relevant lane context prepared"],control:"Inactivity and contact cooldown"}
] as const;
export function BotExplorer(){
 const [selected,setSelected]=useState(0); const [showHistory,setShowHistory]=useState(false);const bot=bots[selected];
 function choose(i:number){setSelected(i);setShowHistory(false)}
 return <section className="pvl-bots pvl-wrap" id="bot-roster"><p className="pvl-eyebrow">Meet your operations team</p><h2>Specialists for the work<br/><em>that never stops.</em></h2><p className="pvl-section-lead">Choose a bot. Follow the trigger, the work, and the next decision.</p>
 <div className="pvl-bot-tabs" role="tablist" aria-label="Explore AI bots">{bots.map((b,i)=><button key={b.id} type="button" role="tab" id={"tab-"+b.id} aria-controls="bot-panel" aria-selected={i===selected} tabIndex={i===selected?0:-1} onClick={()=>choose(i)} onKeyDown={e=>{let n=i;if(e.key==="ArrowRight")n=(i+1)%bots.length;else if(e.key==="ArrowLeft")n=(i+bots.length-1)%bots.length;else if(e.key==="Home")n=0;else if(e.key==="End")n=bots.length-1;else return;e.preventDefault();choose(n);document.getElementById("tab-"+bots[n].id)?.focus()}}><span className="pvl-bot-glyph" aria-hidden="true"><VisualIcon name={b.id==="margin"||b.id==="price"?"chart":b.id==="match"||b.id==="return"?"people":"message"}/></span><strong>{b.name}</strong><small>{b.tag}</small><span className="pvl-selected-line"/></button>)}</div>
 <div className="pvl-bot-detail" role="tabpanel" id="bot-panel" aria-labelledby={"tab-"+bot.id} tabIndex={0}>
 <div className="pvl-bot-copy"><p className="pvl-eyebrow">{bot.name}</p><h3>{bot.headline}</h3><p>{bot.body}</p><ol className="pvl-vertical-steps">{[bot.trigger,bot.work,bot.result].map((s,i)=><li key={s}><span>{i+1}</span>{s}</li>)}</ol><Link href="/contact?type=demo" className="pvl-text-link">See this workflow in a demo ↗</Link></div>
 <div className="pvl-example"><div className="pvl-example-top"><span>PREVAYL <b>/</b> {bot.name}</span><span className="pvl-pill">Illustrative walkthrough</span></div><div className="pvl-example-inner"><p className="pvl-eyebrow">Example · DEMO-1042</p><h4>{selected===0?"Review the economics.":bot.name+" at work."}</h4><BotVisual id={bot.id}/><div className="pvl-example-metrics">{bot.labels.map((l,i)=><div key={l}><span>{l}</span><strong>{bot.values[i]}</strong></div>)}</div>{selected===0&&<div className="pvl-margin-track" aria-label="Customer price split: carrier cost 92 percent, gross margin 8 percent"><span/><b/></div>}<div className="pvl-example-alert"><span aria-hidden="true">◇</span><div><strong>{bot.notice}</strong><p>{bot.detail}</p></div></div><button className="pvl-button secondary" type="button" aria-expanded={showHistory} onClick={()=>setShowHistory(!showHistory)}>{showHistory?"Hide":"Show"} example activity {showHistory?"−":"+"}</button>{showHistory&&<ol className="pvl-activity">{bot.history.map((h,i)=><li key={h}><span>0{i+1}</span>{h}<small>Example</small></li>)}</ol>}<p className="pvl-example-note">Sample data and explanatory interface. No orders or messages are created.</p></div></div>
 </div><div className="pvl-control-strip"><div><span>Configure</span><strong>{bot.control}</strong></div><div><span>Confirm</span><strong>Enabled actions and permissions</strong></div><div><span>Review</span><strong>Activity and exceptions</strong></div></div></section>
}
