"use client";
import {useState} from "react";
import {CarrierScreens} from "./CarrierScreens";

const resources=[
 {name:"Driver",tag:"01 / People",headline:"A named owner for the movement.",description:"Review the driver against the job before confirming the assignment.",fields:[["Roster","Company drivers & owner-operators"],["Movement","Pickup through final delivery"],["Handoff","Load instructions & documents"]]},
 {name:"Equipment",tag:"02 / Capacity",headline:"The equipment has to fit the work.",description:"Review the truck and trailer alongside the vehicles and stops in the planned load.",fields:[["Power unit","Truck record & operating status"],["Trailer","Configuration & capacity"],["Load","Vehicles & stop sequence"]]},
 {name:"Instructions",tag:"03 / Execution",headline:"Give the driver the context to execute.",description:"Review the pickup requirements, delivery expectations and supporting documents together.",fields:[["Pickup","Location & receiving window"],["Delivery","Destination & contact instructions"],["Documents","Records needed for the movement"]]}
];
const documents=[
 {name:"Bill of lading",code:"BOL",title:"The movement record",description:"Review the vehicle and route details that identify the shipment.",fields:["Shipment reference","Vehicle identification","Pickup & delivery locations","Transport instructions"],handoff:"A clear record of what is moving."},
 {name:"Proof of delivery",code:"POD",title:"The completion record",description:"Review the available delivery evidence before closing out the movement.",fields:["Shipment reference","Delivery date & location","Receiver acknowledgement","Supporting delivery notes"],handoff:"Evidence for billing and pay review."},
 {name:"Exceptions",code:"REVIEW",title:"The details that need attention",description:"Keep missing documents and delivery discrepancies visible during office review.",fields:["Missing documentation","Condition or delivery notes","Supporting photographs, if available","Follow-up required"],handoff:"Resolve open questions before closeout."}
];
export function CarrierStageVisual({kind}:{kind:"assignment"|"delivery"}){
 const [selected,setSelected]=useState(0);const assignment=kind==="assignment";const resource=resources[selected];const doc=documents[selected];
 return <div className={"csv "+(assignment?"csv-assignment":"csv-delivery")}>
  <header className="csv-heading"><div><span className="csv-kicker">PREVAYL / {assignment?"Dispatch handoff":"Delivery closeout"}</span><h4>{assignment?"One load. A coordinated team.":"Every delivery needs a record."}</h4></div><span className="csv-disclosure">Interactive workflow illustration</span></header>
  {assignment?<div className="csv-assignment-body">
   <div className="csv-load"><span className="csv-kicker">The planned movement</span><strong>LOAD<br/><em>REQUIREMENTS</em></strong><div className="csv-route"><span><i/>Pickup</span><div/><span><i/>Delivery</span></div><dl><div><dt>Vehicles</dt><dd>What needs to move</dd></div><div><dt>Stops</dt><dd>Where & in what order</dd></div><div><dt>Windows</dt><dd>When the team is expected</dd></div></dl><span className="csv-load-foot">Context carried into assignment <b>↗</b></span></div>
   <div className="csv-resource"><div className="csv-selector" aria-label="Explore assignment requirements">{resources.map((r,i)=><button key={r.name} aria-pressed={selected===i} onClick={()=>setSelected(i)}><span>0{i+1}</span>{r.name}</button>)}</div><div className="csv-resource-detail" aria-live="polite"><span className="csv-kicker">{resource.tag}</span><h5>{resource.headline}</h5><p>{resource.description}</p><dl>{resource.fields.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div><div className="csv-endpoint"><span>Office → driver</span><strong>Assignment with context</strong></div></div>
  </div>:<div className="csv-delivery-body"><div className="csv-doc-selector" aria-label="Explore delivery records">{documents.map((d,i)=><button key={d.code} aria-pressed={selected===i} onClick={()=>setSelected(i)}><span>{d.code}</span><strong>{d.name}</strong><b>↗</b></button>)}</div><div className="csv-document-stage"><div className="csv-paper-back"/><div className="csv-paper"><div className="csv-paper-top"><span>PREVAYL</span><b>{doc.code}</b></div><span className="csv-kicker">Document review / {String(selected+1).padStart(2,"0")}</span><h5>{doc.name}</h5><div className="csv-paper-fields">{doc.fields.map((field,i)=><div key={field}><span>0{i+1}</span><strong>{field}</strong><i/></div>)}</div><footer>Illustrative document structure<span>No customer document shown</span></footer></div></div><div className="csv-document-review"><div className="csv-review-copy" aria-live="polite"><span className="csv-kicker">Office review</span><h5>{doc.title}</h5><p>{doc.description}</p></div><div className="csv-endpoint"><span>Delivery → financial review</span><strong>{doc.handoff}</strong></div></div></div>}
  <footer className="csv-footer"><span>{assignment?"DRIVER + EQUIPMENT + INSTRUCTIONS":"MOVEMENT + EVIDENCE + REVIEW"}</span><p>{assignment?"Explore the three parts of the handoff above.":"Select a record type to explore its role in closeout."} This is a workflow explanation, not a live operational screen.</p></footer>
  <details className="cw-edi csv-source"><summary>{assignment?"View the actual driver-assignment control":"View the actual POD upload control"}</summary><CarrierScreens initial={kind} fixed/></details>
 </div>
}
