"use client";
import {useEffect,useState} from "react";
import {CarrierStageVisual} from "./CarrierStageVisual";
import Link from "next/link";
import {carrierWorkflow} from "@/content/carrier-workflow";
import {CarrierScreens, type CarrierView} from "./CarrierScreens";
const screens:Record<string,CarrierView>={intake:"intake",assignment:"assignment",delivery:"delivery",gm:"gm",builder:"builder",map:"map",reconciliation:"settlements"};
export function CarrierWorkflow(){const [active,setActive]=useState(0);useEffect(()=>{const restore=()=>{const id=new URLSearchParams(window.location.search).get("step");const index=carrierWorkflow.findIndex(s=>s.id===id);setActive(index<0?0:index)};restore();window.addEventListener("popstate",restore);return()=>window.removeEventListener("popstate",restore)},[]);const select=(next:number)=>{setActive(next);const url=new URL(window.location.href);url.searchParams.set("step",carrierWorkflow[next].id);window.history.replaceState(window.history.state,"",url)};const step=carrierWorkflow[active];const advance=(next:number)=>{select(next);requestAnimationFrame(()=>document.getElementById("cw-panel")?.scrollIntoView({block:"start",behavior:"instant"}))};return <>
<section className="pvl-wrap cw-hero"><p className="pvl-eyebrow">Carrier TMS / The business behind the fleet</p><h1>From incoming freight<br/>to <em>driver settlement.</em></h1><div className="cw-hero-bottom"><p>Run customer orders, load planning, equipment, drivers and financial review through one operating cycle. Your load board is one source of work. Your TMS runs the company that moves it.</p><div className="pvl-actions"><Link className="pvl-button" href="/contact?type=demo&role=carriers">Book a fleet operations demo ↗</Link><a className="pvl-text-link" href="#carrier-workflow">Explore the workflow ↓</a></div></div></section>
<section className="pvl-wrap pvl-section" id="carrier-workflow" aria-labelledby="cw-title"><div className="pvl-section-heading"><div><p className="pvl-eyebrow">One operating cycle / Six connected steps</p><h2 id="cw-title">Follow the work.<br/><em>Keep the context.</em></h2></div><p>Select a step to see the decisions, records and handoff involved. Actual carrier screens show the workspaces behind the process.</p></div>
<div className="cw-tabs" role="tablist" aria-label="Carrier operating cycle">{carrierWorkflow.map((s,i)=><button key={s.id} type="button" role="tab" id={"cw-tab-"+s.id} aria-selected={active===i} aria-controls="cw-panel" tabIndex={active===i?0:-1} onClick={()=>select(i)} onKeyDown={e=>{let n=active;if(e.key==="ArrowRight")n=(active+1)%6;else if(e.key==="ArrowLeft")n=(active+5)%6;else if(e.key==="Home")n=0;else if(e.key==="End")n=5;else return;e.preventDefault();select(n);document.getElementById("cw-tab-"+carrierWorkflow[n].id)?.focus()}}><span>0{i+1}</span><strong>{s.label}</strong></button>)}</div>
<div className="cw-panel" id="cw-panel" role="tabpanel" aria-labelledby={"cw-tab-"+step.id}><div className="cw-context"><div><p className="pvl-eyebrow">0{active+1} / {step.label}</p><h3>{step.title}</h3></div><p className="cw-intro">{step.body}</p></div>{screens[step.screen]&&<div className="cw-screen">{step.screen==="assignment"||step.screen==="delivery"?<CarrierStageVisual key={step.screen} kind={step.screen}/>:<CarrierScreens key={step.screen} initial={screens[step.screen]} fixed/>}{step.id==="intake"&&<details className="cw-edi"><summary>See the GM VTIMS / EDI connection workspace</summary><CarrierScreens initial="gm" fixed/></details>}</div>}<div className="cw-review"><details><summary>Review checklist <span>3 checkpoints</span></summary><ul>{step.checks.map(c=><li key={c}>{c}</li>)}</ul></details><div className="cw-handoff"><span>Next handoff</span><strong>{step.handoff} →</strong></div><a className="cw-step-link" href={"?step="+step.id+"#carrier-workflow"}>Link to this step ↗</a></div><div className="cw-controls"><button type="button" disabled={active===0} onClick={()=>advance(active-1)}>← Previous step</button><span>0{active+1} / 06</span><button type="button" disabled={active===5} onClick={()=>advance(active+1)}>Next step →</button></div></div></section>
<section className="pvl-wrap pvl-section cw-connections"><div><p className="pvl-eyebrow">Connected to the way your fleet works</p><h2>Your providers.<br/>Your customers.<br/><em>Your operation.</em></h2></div><div><article><h3>ELD positions on the operations map</h3><p>Supported ELD connections bring vehicle positions into fleet visibility. Reporting timestamps matter: review freshness alongside available vehicle and load context.</p><Link className="pvl-text-link" href="/solutions/carriers#section-1">Explore fleet visibility →</Link></article><article><h3>EDI and OEM freight exchange</h3><p>Review partner-specific tender and status workflows, including GM VTIMS. Connection scope, transaction mapping, credentials and partner acceptance are part of setup.</p><Link className="pvl-text-link" href="/platform/integrations/vtims-edi">Explore VTIMS and EDI →</Link></article><article><h3>Customer billing and driver pay</h3><p>Customer invoices, company expenses and driver settlements answer different financial questions. Keep each tied to its supporting operational records.</p><Link className="pvl-text-link" href="/platform/accounting">Explore accounting →</Link></article></div></section>
<section className="pvl-wrap cw-close"><div><p className="pvl-eyebrow">Make the demo match your company</p><h2>Bring a lane.<br/><em>Walk through the whole job.</em></h2><p>Bring your fleet size, ELD provider, OEM requirements and a driver pay example. Review the workflow, data and setup your team needs.</p></div><Link className="pvl-button" href="/contact?type=demo&role=carriers">Plan your carrier demo ↗</Link></section>
</>}
