"use client";
import { useState,useEffect,FormEvent } from "react";
export function ContactForm({defaultSubject="Book a demo"}:{defaultSubject?:string}={}){
 const [busy,setBusy]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState(""),[subject,setSubject]=useState(defaultSubject),[preview,setPreview]=useState(true),[role,setRole]=useState("");
 useEffect(()=>{const q=new URLSearchParams(window.location.search);const roles:Record<string,string>={brokers:"Broker",carriers:"Carrier / Owner-operator",dealers:"Dealer",wholesale:"Auction / Wholesale"};setRole(roles[q.get("role")||""]||"");setSubject(q.get("type")==="support"?"Support":q.get("type")==="sales"?"Pricing inquiry":q.get("type")==="partner"?"Partner inquiry":defaultSubject);setPreview(!["prevaylos.com","www.prevaylos.com"].includes(window.location.hostname))},[defaultSubject]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");if(preview){setError("This is the design preview. Your message has not been sent.");return}if(busy||sent)return;const form=e.currentTarget;const data=new FormData(form);setBusy(true);
 try{const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:data.get("name"),email:data.get("email"),company:data.get("company"),phone:data.get("phone"),subject,message:"Role: "+data.get("role")+"\nMonthly vehicles: "+data.get("volume")+"\n\n"+data.get("message")})});const result=await response.json();if(!response.ok||result.success!==true||result.stored!==true)throw new Error("We couldn’t submit your request. Please try again.");setSent(true)}catch{setError("We couldn’t submit your request. Your details are still here. Please try again.")}finally{setBusy(false)}}
 return <form className="pvl-form" onSubmit={submit}><h2 style={{fontSize:"2.4rem",marginBottom:25}}>Let’s talk through your operation.</h2>{preview&&<p className="pvl-form-note" style={{marginBottom:22}}>Design preview — submissions are disabled.</p>}<div className="pvl-form-grid">
 <div className="pvl-field"><label htmlFor="contact-name">Name *</label><input autoComplete="name" id="contact-name" name="name" required maxLength={120}/></div>
 <div className="pvl-field"><label htmlFor="contact-email">Work email *</label><input autoComplete="email" type="email" id="contact-email" name="email" required maxLength={200}/></div>
 <div className="pvl-field"><label htmlFor="contact-company">Company</label><input autoComplete="organization" id="contact-company" name="company" maxLength={200}/></div>
 <div className="pvl-field"><label htmlFor="contact-phone">Phone</label><input autoComplete="tel" type="tel" id="contact-phone" name="phone" maxLength={40}/></div>
 <div className="pvl-field"><label htmlFor="contact-role">Your role</label><select id="contact-role" name="role" value={role} onChange={e=>setRole(e.target.value)}><option value="">Select your role</option><option>Broker</option><option>Carrier / Owner-operator</option><option>Dealer</option><option>Auction / Wholesale</option><option>Other</option></select></div>
 <div className="pvl-field"><label htmlFor="contact-volume">Vehicles per month</label><input id="contact-volume" name="volume" type="number" min="0" step="1" placeholder="e.g. 50"/></div>
 <div className="pvl-field full"><label htmlFor="contact-subject">How can we help?</label><select id="contact-subject" value={subject} onChange={e=>setSubject(e.target.value)}><option>Book a demo</option><option>Pricing inquiry</option><option>Support</option><option>Partner inquiry</option></select></div>
 <div className="pvl-field full"><label htmlFor="contact-message">What would you like to work through? *</label><textarea id="contact-message" name="message" required maxLength={5000} placeholder="Your lanes, current tools, or the workflow you want to improve."/></div></div>
 <button type="submit" className="pvl-button" disabled={busy||sent} aria-describedby="contact-status">{busy?"Submitting…":sent?"Request submitted":"Request a conversation ↗"}</button>
 <div id="contact-status" aria-live="polite">{error&&<p className="pvl-form-status error">{error}</p>}{sent&&<p className="pvl-form-status">Your request was received and saved for our team. Thank you for getting in touch.</p>}</div><p className="pvl-form-note">Fields marked * are required.</p></form>
}
