"use client";
 import { useState,useEffect,useRef,FormEvent } from "react";
export function ContactForm({defaultSubject="Book a demo"}:{defaultSubject?:string}={}){
 const [busy,setBusy]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState(""),[subject,setSubject]=useState(defaultSubject),[preview,setPreview]=useState(true),[role,setRole]=useState("");
 const confirmation=useRef<HTMLHeadingElement>(null);const isDealer=role==="Dealer";const isCarrier=role==="Carrier / Owner-operator";const carrierDemo=role==="Carrier / Owner-operator"&&subject==="Book a demo";useEffect(()=>{if(sent)confirmation.current?.focus()},[sent]);
 useEffect(()=>{const q=new URLSearchParams(window.location.search);const roles:Record<string,string>={brokers:"Broker",carriers:"Carrier / Owner-operator",dealers:"Dealer",wholesale:"Auction / Wholesale"};setRole(roles[q.get("role")||""]||"");setSubject(q.get("type")==="support"?"Support":q.get("type")==="sales"?"Pricing inquiry":q.get("type")==="partner"?"Partner inquiry":defaultSubject);setPreview(!["prevaylos.com","www.prevaylos.com"].includes(window.location.hostname))},[defaultSubject]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");if(preview){setError("This is the design preview. Your message has not been sent.");return}if(busy||sent)return;const form=e.currentTarget;const data=new FormData(form);setBusy(true);
 try{const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:data.get("name"),email:data.get("email"),company:data.get("company"),phone:data.get("phone"),subject,message:["Role: "+(data.get("role")||"Not specified"),"Monthly vehicles: "+(data.get("volume")||"Not specified"),...(isCarrier?["Operation: Carrier TMS","Fleet size: "+(data.get("fleet")||"Not specified"),"ELD provider: "+(data.get("eld")||"Not specified"),"OEM / EDI requirements: "+(data.get("edi")||"Not specified"),"Current tools: "+(data.get("tools")||"Not specified")]:[]),...(isDealer?["Rooftops: "+(data.get("rooftops")||"Not specified"),"Users: "+(data.get("users")||"Not specified")]:[]),"","Operational challenge / request:",data.get("message")].join("\n")})});const result=await response.json();if(!response.ok||result.success!==true||result.stored!==true)throw new Error("We couldn’t submit your request. Please try again.");setSent(true)}catch{setError("We couldn’t submit your request. Your details are still here. Please try again.")}finally{setBusy(false)}}
 if(sent)return <section className="pvl-form contact-confirmation" aria-live="polite"><p className="pvl-eyebrow">Request saved</p><h2 ref={confirmation} tabIndex={-1}>{carrierDemo?"Your fleet demo request is in.":"Thank you for getting in touch."}</h2><p>Your details have been saved for the Prevayl team.{subject==="Book a demo"&&" A demo time has not been booked yet."}</p><h3>What happens next</h3><ol><li>We review your operation and the workflows you want to explore.</li><li>Our team follows up using the contact details you provided to coordinate next steps.</li><li>{carrierDemo?"We shape the walkthrough around your fleet, integrations and driver-pay process.":"We focus the conversation on your questions and requirements."}</li></ol><a className="pvl-text-link" href={carrierDemo?"/platform/carriers#carrier-workflow":"/platform"}>Explore the platform while you wait →</a></section>;
 return <form className="pvl-form" onSubmit={submit}><h2 style={{fontSize:"2.4rem",marginBottom:25}}>{carrierDemo?"Plan your fleet demo.":"Let’s talk through your operation."}</h2>{carrierDemo&&<p className="pvl-form-note contact-intro">Tell us about your fleet so we can focus on the workflows that matter. Integration details are optional.</p>}{preview&&<p className="pvl-form-note" style={{marginBottom:22}}>Design preview — submissions are disabled.</p>}<div className="pvl-form-grid">
 <div className="pvl-field"><label htmlFor="contact-name">Name *</label><input autoComplete="name" id="contact-name" name="name" required maxLength={120}/></div>
 <div className="pvl-field"><label htmlFor="contact-email">Work email *</label><input autoComplete="email" type="email" id="contact-email" name="email" required maxLength={200}/></div>
 <div className="pvl-field"><label htmlFor="contact-company">Company</label><input autoComplete="organization" id="contact-company" name="company" maxLength={200}/></div>
 <div className="pvl-field"><label htmlFor="contact-phone">Phone</label><input autoComplete="tel" type="tel" id="contact-phone" name="phone" maxLength={40}/></div>
 <div className="pvl-field"><label htmlFor="contact-role">Your role</label><select id="contact-role" name="role" value={role} onChange={e=>setRole(e.target.value)}><option value="">Select your role</option><option>Broker</option><option>Carrier / Owner-operator</option><option>Dealer</option><option>Auction / Wholesale</option><option>Other</option></select></div>
 {!isDealer&&<div className="pvl-field"><label htmlFor="contact-volume">Vehicles per month</label><input id="contact-volume" name="volume" type="number" min="0" step="1" placeholder="e.g. 50"/></div>}
 <div className="pvl-field full"><label htmlFor="contact-subject">How can we help?</label><select id="contact-subject" value={subject} onChange={e=>setSubject(e.target.value)}><option>Book a demo</option><option>Pricing inquiry</option><option>Support</option><option>Partner inquiry</option></select></div>
 {isDealer&&<fieldset className="contact-fleet full"><legend>Your dealership</legend><div className="pvl-form-grid">
 <div className="pvl-field"><label htmlFor="contact-dealer-volume">Cars moved per month</label><select id="contact-dealer-volume" name="volume" defaultValue=""><option value="">Select monthly volume</option>{["1–25","26–50","51–100","101–250","251–500","501–1,000","1,001+","Not sure yet"].map(value=><option key={value}>{value}</option>)}</select></div>
 <div className="pvl-field"><label htmlFor="contact-rooftops">Number of rooftops</label><select id="contact-rooftops" name="rooftops" defaultValue=""><option value="">Select rooftops</option>{["1","2–5","6–10","11–25","26–50","51+","Not sure yet"].map(value=><option key={value}>{value}</option>)}</select></div>
 <div className="pvl-field"><label htmlFor="contact-users">Number of users</label><select id="contact-users" name="users" defaultValue=""><option value="">Select users</option>{["1","2–5","6–10","11–25","26–50","51–100","101+","Not sure yet"].map(value=><option key={value}>{value}</option>)}</select></div>
 </div></fieldset>}
 {isCarrier&&<fieldset className="contact-fleet full"><legend>Your fleet & connections</legend><div className="pvl-form-grid"><div className="pvl-field"><label htmlFor="contact-fleet">Number of trucks{carrierDemo?" *":""}</label><select id="contact-fleet" name="fleet" required={carrierDemo} defaultValue=""><option value="" disabled>Select fleet size</option><option>1 truck</option><option>2–10 trucks</option><option>11–25 trucks</option><option>26–50 trucks</option><option>51–100 trucks</option><option>101+ trucks</option><option>Planning a fleet</option></select></div><div className="pvl-field"><label htmlFor="contact-eld">ELD / telematics provider</label><input id="contact-eld" name="eld" maxLength={160} placeholder="e.g. Geotab, Samsara, or none"/></div><div className="pvl-field full"><label htmlFor="contact-edi">OEM / EDI connections needed</label><input id="contact-edi" name="edi" maxLength={400} placeholder="e.g. GM VTIMS, another partner, or not sure"/></div><div className="pvl-field full"><label htmlFor="contact-tools">Current dispatch or accounting tools</label><input id="contact-tools" name="tools" maxLength={300} placeholder="Optional — tell us what you use today"/></div></div></fieldset>}
 <div className="pvl-field full"><label htmlFor="contact-message">{carrierDemo?"What is your biggest operational challenge? *":"What would you like to work through? *"}</label><textarea id="contact-message" name="message" required maxLength={5000} placeholder={carrierDemo?"What slows your team down? Load planning, tracking, OEM freight, driver pay—or something else?":"Your lanes, current tools, or the workflow you want to improve."}/></div></div>
 <button type="submit" className="pvl-button" disabled={busy||sent} aria-describedby="contact-status">{busy?"Submitting…":sent?"Request submitted":carrierDemo?"Request my fleet demo ↗":"Request a conversation ↗"}</button>
 <div id="contact-status" aria-live="polite">{error&&<p className="pvl-form-status error">{error}</p>}{sent&&<p className="pvl-form-status">Your request was received and saved for our team. Thank you for getting in touch.</p>}</div><p className="pvl-form-note">Fields marked * are required.</p></form>
}


