"use client";
import {useState} from "react";
import Link from "next/link";
import {customerJourneys,customerQuestions} from "@/content/customer-journeys";
import {CarrierScreens} from "./CarrierScreens";
import {Screen} from "./Screen";

export function CustomerExperience(){
 const [active,setActive]=useState(0);const journey=customerJourneys[active];
 return <>
 <section className="cx-hero pvl-wrap">
  <div><p className="pvl-eyebrow">Customers / Built around your operation</p><h1>Different businesses.<br/><em>One connected movement.</em></h1><p className="cx-lead">You may own the trucks, coordinate the carriers, buy the vehicles or run the receiving lot. Prevayl connects the work around your part of the movement.</p><div className="pvl-actions"><a className="pvl-button" href="#customer-workflows">Find your workflow ↓</a><Link className="pvl-text-link" href="/contact?type=demo">Talk through your operation ↗</Link></div></div>
  <aside className="cx-hero-note"><span className="pvl-eyebrow">The work stays connected</span><div className="cx-record"><span>01 / THE REQUEST</span><strong>Vehicle. Customer. Destination.</strong></div><div className="cx-record"><span>02 / THE MOVEMENT</span><strong>Load. Carrier. Driver.</strong></div><div className="cx-record"><span>03 / THE CLOSE</span><strong>Delivery. Documents. Money.</strong></div><p>A shared operating record, with the perspective and permissions each team needs.</p></aside>
 </section>
 <nav className="cx-page-nav pvl-wrap" aria-label="Customer page sections"><a href="#customer-workflows">Your business</a><a href="#customer-product">Inside the platform</a><a href="#customer-onboarding">Getting started</a><a href="#customer-questions">Common questions</a></nav>
 <section className="pvl-section pvl-wrap" id="customer-workflows" aria-labelledby="cx-workflow-title"><div className="pvl-section-heading"><div><p className="pvl-eyebrow">Start with your seat at the table</p><h2 id="cx-workflow-title">What does your team<br/><em>need to control?</em></h2></div><p>Choose your business to see the daily workflow, the relevant workspace and what to bring to your demo.</p></div>
 <div className="cx-tabs" role="tablist" aria-label="Choose your business">{customerJourneys.map((j,i)=><button type="button" role="tab" key={j.id} id={"cx-tab-"+j.id} aria-selected={active===i} aria-controls="cx-journey" tabIndex={active===i?0:-1} onClick={()=>setActive(i)} onKeyDown={e=>{let next=active;if(e.key==="ArrowRight")next=(active+1)%customerJourneys.length;else if(e.key==="ArrowLeft")next=(active+customerJourneys.length-1)%customerJourneys.length;else if(e.key==="Home")next=0;else if(e.key==="End")next=customerJourneys.length-1;else return;e.preventDefault();setActive(next);document.getElementById("cx-tab-"+customerJourneys[next].id)?.focus()}}><span className="cx-index">0{i+1}</span><strong>{j.label}</strong><small>{j.short}</small></button>)}</div>
 <div className="cx-journey" role="tabpanel" id="cx-journey" aria-labelledby={"cx-tab-"+journey.id}>
  <div className="cx-intro"><div><p className="pvl-eyebrow">{journey.label}</p><h3>{journey.title}</h3><p>{journey.intro}</p></div><aside><span>The daily question</span><p>{journey.question}</p><ul>{journey.focus.map(f=><li key={f}>{f}</li>)}</ul></aside></div>
  <div className="cx-steps">{journey.steps.map((step,i)=><article key={step.title}><span className="cx-index">0{i+1}</span><h4>{step.title}</h4><p>{step.body}</p></article>)}</div>
  <div className="cx-demo"><div><span className="pvl-eyebrow">Make the demo useful</span><p>{journey.demo}</p></div><div className="pvl-actions"><Link className="pvl-button" href={"/contact?type=demo&role="+journey.id}>See it for your business ↗</Link><Link className="pvl-text-link" href={journey.link}>Explore {journey.label.toLowerCase()} →</Link></div></div>
  <div className="cx-product" id="customer-product"><div className="cx-product-heading"><p className="pvl-eyebrow">Inside the platform / {journey.label}</p><p>{journey.view==="carrier"?"Explore the actual carrier dashboard, fleet map and GM VTIMS workspace.":journey.view==="broker"?"The operations workspace behind customer, carrier and order coordination.":"The operations-side order workspace behind vehicle coordination. Your portal presents the records and actions permitted for your account."}</p></div>{journey.view==="carrier"?<CarrierScreens initial="dashboard"/>:<Screen key={journey.id} src={journey.view==="broker"?"/screenshots/platform/dispatch.png":"/screenshots/platform/orders.png"} title={journey.view==="broker"?"Broker operations":"Operations-side order coordination"} caption={journey.view==="broker"?"Actual platform capture of the dispatch workspace.":"Actual operations-console capture; this is not a screenshot of the dealer or auction portal."}/>}</div>
 </div></section>
 <section className="cx-onboarding pvl-section pvl-wrap" id="customer-onboarding"><div className="pvl-section-heading"><div><p className="pvl-eyebrow">From evaluation to everyday work</p><h2>Bring your operation.<br/><em>Build the rollout around it.</em></h2></div><p>A useful evaluation starts with the work your team already does. Agree the scope before moving into setup.</p></div><ol className="cx-rollout">{[["Walk through the work","Show your lanes, vehicle mix, team roles and the handoffs that slow you down."],["Review the fit","See the relevant workflows. Confirm modules, data needs, integrations and account terms."],["Prepare the records","Agree imports, field mapping, user permissions and the checks needed before rollout."],["Put the team to work","Review the workflow with your users and agree training, launch steps and support."]].map(([title,body],i)=><li key={title}><span className="cx-index">0{i+1}</span><h3>{title}</h3><p>{body}</p></li>)}</ol></section>
 <section className="cx-faq pvl-section pvl-wrap" id="customer-questions"><div><p className="pvl-eyebrow">Before we talk</p><h2>Good questions.<br/><em>Clear starting points.</em></h2><p>Bring your specific requirements. We’ll work through the details with you.</p></div><div>{customerQuestions.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
 <section className="cx-close pvl-wrap"><p className="pvl-eyebrow">Your operation is the starting point</p><h2>Show us the handoff<br/><em>you want to improve.</em></h2><p>A load that took too many calls. A driver settlement that took too long. A vehicle your team could not locate. Start there.</p><Link className="pvl-button" href={"/contact?type=demo&role="+journey.id}>Book your {journey.id==="carriers"?"fleet":journey.id==="brokers"?"brokerage":journey.id==="dealers"?"dealership":"wholesale"} demo ↗</Link></section>
 </>;
}
