"use client";
import {useState} from "react";
import states from "@/content/fleet-map-paths.json";
const positions=[{id:"TRK-104",city:"Louisville",lon:-85.759,lat:38.253},{id:"TRK-208",city:"Chicago",lon:-87.630,lat:41.878},{id:"TRK-312",city:"Columbus",lon:-82.999,lat:39.961},{id:"TRK-416",city:"Dallas",lon:-96.797,lat:32.777}];
const destinations=[[-86.782,36.163],[-84.388,33.749],[-80.843,35.227],[-96.797,32.777]];
const xy=(lon:number,lat:number)=>[(lon+102)*32,(45-lat)*38];
export function FleetMap({selected,onSelect}:{selected:number;onSelect:(i:number)=>void}){
 const current=positions[selected],start=xy(current.lon,current.lat),end=xy(...destinations[selected] as [number,number]);
 return <div className="fm-map"><div className="fm-map-bar"><div><b>ELD → LIVE FLEET MAP</b><span>Vehicle positions populate the map from the connected provider.</span></div><span className="fw-demo">SAMPLE POSITIONS</span></div><div className="fm-geography"><svg viewBox="0 0 900 650" aria-label="Fleet positions on a geographic map of the central and eastern United States" role="img"><rect width="900" height="650" fill="#101f2b"/>{states.map(s=><path key={s.name} d={s.path} fill="#1c2c3b" stroke="#3b4d5e" strokeWidth="1"/>)}{[["TEXAS",-99,32],["OKLAHOMA",-98,35.5],["ARKANSAS",-92.7,34.9],["MISSOURI",-92.5,38.5],["ILLINOIS",-89.3,40],["INDIANA",-86.4,40],["OHIO",-82.6,40.9],["TENNESSEE",-86,35.7],["GEORGIA",-83.5,32.5],["MICHIGAN",-85.5,43.2],["KENTUCKY",-84.8,37.3],["ALABAMA",-86.9,32.7]].map(([name,lon,lat])=>{const [x,y]=xy(Number(lon),Number(lat));return <text key={name} x={x} y={y} textAnchor="middle" fill="#8295a7" fontSize="10" letterSpacing="1.5">{name}</text>})}<path d={`M${start.join(",")}L${end.join(",")}`} stroke="#d6b65c" strokeWidth="2" strokeDasharray="6 6" fill="none"/><circle cx={end[0]} cy={end[1]} r="5" fill="#111c28" stroke="#d6b65c" strokeWidth="2"/>{positions.map((p,i)=>{const [x,y]=xy(p.lon,p.lat);return <g key={p.id} role="button" tabIndex={0} aria-label={`Select ${p.id} in ${p.city}`} aria-pressed={selected===i} onClick={()=>onSelect(i)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onSelect(i)}}} className="fm-pin"><circle cx={x} cy={y} r={selected===i?19:14} fill={i===2?"#665232":selected===i?"#c9a84c":"#233d50"} stroke={selected===i?"#f0d891":"#a8c4d8"} strokeWidth="2"/><text x={x} y={y+4} textAnchor="middle" fontSize="11" fill={selected===i?"#101820":"#f0f4f8"} fontWeight="700">{i+1}</text><rect x={x+24} y={y-19} width="98" height="40" rx="4" fill="#101a25" stroke={selected===i?"#a18a4d":"#344b60"}/><text x={x+33} y={y-3} fill="#e7edf3" fontSize="11">{p.id}</text><text x={x+33} y={y+12} fill="#abc1d4" fontSize="10">{p.city}</text></g>})}</svg><div className="fm-legend"><span><i/> ELD vehicle position</span><span><i className="fm-amber"/> Stale report</span><span>Dashed line: destination context, not road routing</span></div></div><div className="fm-position-buttons" aria-label="Select a mapped truck">{positions.map((p,i)=><button type="button" key={p.id} aria-pressed={selected===i} onClick={()=>onSelect(i)}>{p.id}<span>{p.city}</span></button>)}</div></div>
}
const units=[
 {id:"VIN-1042",vehicle:"SUV",source:"OEM EDI · 204",from:"Detroit, MI",to:"Nashville, TN",rate:850,weight:4400},
 {id:"VIN-1043",vehicle:"Sedan",source:"OEM EDI · 204",from:"Detroit, MI",to:"Nashville, TN",rate:750,weight:3400},
 {id:"VIN-1044",vehicle:"SUV",source:"OEM EDI · 204",from:"Detroit, MI",to:"Nashville, TN",rate:850,weight:4400},
 {id:"VIN-1045",vehicle:"Pickup",source:"Direct customer",from:"Toledo, OH",to:"Nashville, TN",rate:950,weight:5100},
 {id:"VIN-1046",vehicle:"Sedan",source:"Broker order",from:"Toledo, OH",to:"Nashville, TN",rate:700,weight:3400},
 {id:"VIN-1047",vehicle:"SUV",source:"OEM EDI · 204",from:"Detroit, MI",to:"Nashville, TN",rate:850,weight:4400},
];
export function LoadBuilder({onTrack}:{onTrack:()=>void}){
 const [chosen,setChosen]=useState([0,1,2]),[staged,setStaged]=useState(false);
 const picked=units.filter((_,i)=>chosen.includes(i)),revenue=picked.reduce((s,v)=>s+v.rate,0),weight=picked.reduce((s,v)=>s+v.weight,0);
 function toggle(i:number){setStaged(false);setChosen(v=>v.includes(i)?v.filter(n=>n!==i):[...v,i])}
 return <div className="fb-builder"><div className="fb-flow"><span>01 <b>EDI tender mapped to order</b></span><span>02 <b>Select vehicles & build load</b></span><span>03 <b>Assign driver & track</b></span></div><div className="fw-workarea"><div className="fw-primary"><div className="fw-table-scroll" tabIndex={0} aria-label="Selectable vehicle inventory"><table><caption>Build from your order pool · select vehicles to update the plan</caption><thead><tr><th>Select / vehicle</th><th>Order source</th><th>Pickup → delivery</th><th>Revenue</th></tr></thead><tbody>{units.map((u,i)=><tr key={u.id} className={chosen.includes(i)?"fw-selected":""}><td><label className="fb-select"><input type="checkbox" checked={chosen.includes(i)} onChange={()=>toggle(i)} aria-label={`Include ${u.id}`}/><span><b>{u.id}</b><small>{u.vehicle} · {u.weight.toLocaleString()} lb</small></span></label></td><td><span className="fb-source">{u.source}</span></td><td><strong>{u.from}</strong><small>→ {u.to}</small></td><td>${u.rate}</td></tr>)}</tbody></table></div><div className="fw-note">Fictional VIN references and rates. EDI orders enter the planning workflow after partner mapping and tender review.</div></div><aside className="fw-detail fb-plan"><div className="fw-detail-title"><span>LOAD PLAN</span><b>DEMO-1042</b></div><h4>Detroit → Nashville</h4><p>Truck TRK-104 · Alex Morgan</p><div className="fb-deck" aria-label={`${chosen.length} of 9 nominal positions selected`}>{Array.from({length:9},(_,i)=><div key={i} className={i<chosen.length?"occupied":""}><small>{String(i+1).padStart(2,"0")}</small><b>{picked[i]?.vehicle||"Open"}</b></div>)}</div><dl className="fw-ledger"><div><dt>Vehicles selected</dt><dd>{chosen.length} / 9</dd></div><div><dt>Vehicle weight</dt><dd>{weight.toLocaleString()} lb</dd></div><div><dt>Load revenue</dt><dd>${revenue.toLocaleString()}</dd></div></dl><ol className="fb-stop-plan"><li>Detroit · {picked.filter(u=>u.from.startsWith("Detroit")).length} pickups</li>{picked.some(u=>u.from.startsWith("Toledo"))&&<li>Toledo · {picked.filter(u=>u.from.startsWith("Toledo")).length} pickups</li>}<li>Nashville · {chosen.length} deliveries</li></ol><p className="fw-detail-note">Nominal positions shown. Dimensions, axle weights, equipment limits and stop sequence require review.</p><button type="button" className="fb-action" disabled={!chosen.length} onClick={()=>setStaged(true)}>{staged?"Example load staged ✓":"Stage example load"}</button><div role="status" className="fb-status">{staged?`${chosen.length} vehicles staged for assignment review. Demo only; no operational records created.`:"Select vehicles to plan this example movement."}</div><button type="button" className="fb-track" onClick={onTrack}>See this truck on the ELD map →</button></aside></div></div>
}
