"use client";
import {useState} from "react";

type Mode = "dispatch" | "tracking" | "edi" | "finance";
const modes: {id:Mode;label:string;title:string;sub:string}[] = [
 {id:"dispatch",label:"Fleet dispatch",title:"Every truck. Every assignment.",sub:"Explore a fleet plan and select a truck to inspect its trip."},
 {id:"tracking",label:"Tracking & ELD",title:"The road, in context.",sub:"Location, reporting freshness and driver hours in the same operating view."},
 {id:"edi",label:"OEM / EDI",title:"Follow the transaction.",sub:"Trace a tender from partner exchange to the operating record."},
 {id:"finance",label:"Driver reconciliation",title:"Every dollar accounted for.",sub:"Follow load revenue through driver pay, adjustments and settlement review."},
];
const fleet = [
 {truck:"TRK-104",driver:"Alex Morgan",route:"Detroit → Nashville",state:"In transit",vin:8,max:9,revenue:6400, miles:534,location:"Louisville, KY",age:"45 sec",hours:"4h 35m",pickup:"Detroit, MI",delivery:"Nashville, TN",eta:"15:40",pay:1600,expenses:125,advance:200},
 {truck:"TRK-208",driver:"Jordan Lee",route:"Chicago → Atlanta",state:"At pickup",vin:7,max:9,revenue:5950,miles:716,location:"Chicago, IL",age:"1 min",hours:"7h 10m",pickup:"Chicago, IL",delivery:"Atlanta, GA",eta:"Tomorrow · 09:15",pay:1487.5,expenses:80,advance:150},
 {truck:"TRK-312",driver:"Casey Brooks",route:"Columbus → Charlotte",state:"Review required",vin:6,max:7,revenue:4800,miles:425,location:"Columbus, OH",age:"18 min",hours:"2h 20m",pickup:"Columbus, OH",delivery:"Charlotte, NC",eta:"Needs review",pay:1200,expenses:60,advance:100},
 {truck:"TRK-416",driver:"Taylor Reed",route:"Indianapolis → Dallas",state:"Delivered",vin:9,max:9,revenue:7650,miles:899,location:"Dallas, TX",age:"2 min",hours:"5h 05m",pickup:"Indianapolis, IN",delivery:"Dallas, TX",eta:"Delivered · 11:20",pay:1912.5,expenses:140,advance:250},
];
const money=(n:number)=>n.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2});
function Tag({children,warn=false}:{children:React.ReactNode;warn?:boolean}){return <span className={"fw-tag "+(warn?"fw-warn":"")}>{children}</span>}

export function FleetWorkspace({initial="dispatch",fixed=false}:{initial?:Mode;fixed?:boolean}) {
 const [mode,setMode]=useState<Mode>(initial),[selected,setSelected]=useState(0);
 const row=fleet[selected], info=modes.find(m=>m.id===mode)!;
 return <section className="fw-showcase" aria-label={info.label+" interactive example"}>
  {!fixed&&<div className="fw-mode-tabs" role="group" aria-label="Explore fleet workflows">{modes.map((m,i)=><button type="button" key={m.id} onClick={()=>setMode(m.id)} aria-pressed={mode===m.id}><span>0{i+1}</span>{m.label}</button>)}</div>}
  <div className="fw-shell">
   <header className="fw-top"><div className="fw-wordmark">PREVAYL<span>/ FLEET OPERATIONS</span></div><span className="fw-demo">INTERACTIVE PREVIEW · SAMPLE DATA</span></header>
   <div className="fw-title"><div><span className="fw-kicker">OPERATIONS / {info.label.toUpperCase()}</span><h3>{info.title}</h3><p>{info.sub}</p></div><span className="fw-date">EXAMPLE FLEET<br/><b>4 trucks · 30 vehicles</b></span></div>
   <div className="fw-metrics">{(mode==="finance"?[["Load revenue",money(row.revenue)],["Driver earnings",money(row.pay)],["Reimbursements",money(row.expenses)],["Net settlement",money(row.pay+row.expenses-row.advance)]]:mode==="edi"?[["Tender","204"],["Response","990"],["Shipment status","214"],["Acknowledgment","997"]]:[["Assigned vehicles","30"],["Deck positions","34"],["Trip revenue","$24,800"],["Needs attention","01"]]).map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
   {mode==="edi"?<div className="fw-edi">
    <div className="fw-edi-path"><div><small>TRADING PARTNER</small><strong>OEM / logistics network</strong><span>Partner-specific message mapping</span></div><b aria-hidden="true">→</b><div><small>PREVAYL EDI</small><strong>Validate. Map. Acknowledge.</strong><span>Control numbers & transaction history</span></div><b aria-hidden="true">→</b><div><small>OPERATING RECORD</small><strong>Order → dispatch → delivery</strong><span>Shipment events follow the load</span></div></div>
    <div className="fw-table-scroll" tabIndex={0} aria-label="Scrollable workflow table"><table><caption>Example transaction history · DEMO-1042</caption><thead><tr><th>Time</th><th>Transaction</th><th>Direction</th><th>Control reference</th><th>Outcome</th></tr></thead><tbody>{[["08:42:11","204 · Load tender","Inbound","000012401","Mapped to order"],["08:42:12","997 · Acknowledgment","Outbound","000012402","Generated"],["08:48:30","990 · Tender response","Outbound","000012403","Accepted"],["10:16:04","214 · Shipment status","Outbound","000012404","Pickup recorded"]].map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i}>{i===4?<Tag>{v}</Tag>:v}</td>)}</tr>)}</tbody></table></div>
    <footer className="fw-note">Illustrative message sequence. Actual message sets, transport and acceptance requirements depend on your trading partner.</footer>
   </div>:<div className="fw-workarea">
    <div className="fw-primary"><div className="fw-table-scroll" tabIndex={0} aria-label="Scrollable workflow table"><table><caption>{mode==="finance"?"Select a driver settlement":mode==="tracking"?"Vehicle reporting & driver availability":"Fleet assignments · select a truck"}</caption><thead><tr><th>Truck / driver</th><th>{mode==="tracking"?"Last reported position":"Movement"}</th><th>{mode==="finance"?"Driver pay":mode==="tracking"?"Drive time left":"Capacity"}</th><th>{mode==="tracking"?"Report age":"Status"}</th></tr></thead><tbody>{fleet.map((r,i)=><tr className={selected===i?"fw-selected":""} key={r.truck}><td><button type="button" className="fw-row-button" aria-pressed={selected===i} onClick={()=>setSelected(i)}><b>{r.truck}</b><span>{r.driver}</span></button></td><td><strong>{mode==="tracking"?r.location:r.route}</strong><small>{mode==="tracking"?"ELD / telematics example":r.miles+" planned miles · "+money(r.revenue)}</small></td><td>{mode==="finance"?money(r.pay):mode==="tracking"?r.hours:<><span>{r.vin} / {r.max} vehicles</span><div className="fw-capacity" aria-label={r.vin+" of "+r.max+" positions"}>{Array.from({length:r.max},(_,n)=><i key={n} className={n<r.vin?"filled":""}/>)}</div></>}</td><td><Tag warn={i===2}>{mode==="tracking"?r.age:mode==="finance"?"Pending review":r.state}</Tag></td></tr>)}</tbody></table></div>
    <div className="fw-bottom-strip"><span>{mode==="finance"?"Driver pay stays tied to the load.":mode==="tracking"?"Reporting freshness stays visible beside location.":"Customer order → assigned equipment → driver execution"}</span><b>{mode==="tracking"?"1 stale report to review":"Connected operating records"}</b></div></div>
    <aside className="fw-detail" aria-live="polite"><div className="fw-detail-title"><span>{mode==="finance"?"SETTLEMENT REVIEW":"TRIP DETAIL"}</span><b>{row.truck}</b></div><h4>{row.driver}</h4><p>{row.route}</p>
    {mode==="finance"?<><dl className="fw-ledger"><div><dt>Load revenue</dt><dd>{money(row.revenue)}</dd></div><div><dt>Driver share · 25%</dt><dd>{money(row.pay)}</dd></div><div><dt>Reimbursements</dt><dd>+{money(row.expenses)}</dd></div><div><dt>Advance applied</dt><dd>−{money(row.advance)}</dd></div><div className="fw-total"><dt>Net to driver</dt><dd>{money(row.pay+row.expenses-row.advance)}</dd></div></dl><Tag>Pending accounting review</Tag><p className="fw-detail-note">Example pay agreement. Review load records, expenses and adjustments before approval.</p></>:<><ol className="fw-stops"><li><small>PICKUP</small><strong>{row.pickup}</strong><span>Vehicle records & eBOL</span></li><li className="fw-current"><small>{mode==="tracking"?"LAST REPORTED POSITION":"CURRENT STATUS"}</small><strong>{mode==="tracking"?row.location:row.state}</strong><span>{mode==="tracking"?"Reported "+row.age+" ago":row.vin+" vehicles on this movement"}</span></li><li><small>DELIVERY</small><strong>{row.delivery}</strong><span>{row.eta}</span></li></ol>{mode==="tracking"?<div className="fw-hours"><span>Available driving time</span><strong>{row.hours}</strong><small>Example ELD reading · provider coverage varies</small></div>:<div className="fw-document"><span>LOAD RECORD</span><b>Assignment · VINs · eBOL</b><small>One record through delivery</small></div>}</>}
    </aside>
   </div>}
   <footer className="fw-footer"><span>Workflow demonstration. Illustrative interface and fictional operating data.</span><a href="/contact?type=demo">Explore your configured workspace in a demo ↗</a></footer>
  </div>
 </section>;
}
