"use client";
import {useState} from "react";
import Link from "next/link";
import {PageHero} from "@/components/shared/PageHero";
import {CTA} from "./Shared";
export type IntegrationKind="central-dispatch"|"api"|"vtims-edi";
const data={
 "central-dispatch":{eyebrow:"Central Dispatch integration",title:"Your order. The marketplace. Connected.",lead:"Connect Prevayl to Central Dispatch for vehicle listings, carrier dispatches and the information that follows the load.",label:"Central Dispatch",sub:"A marketplace connection inside your operation.",points:[["Listing management","Create, update and remove Central Dispatch listings from the shipment workflow."],["Carrier fulfillment","Connect a carrier commitment to the order. Review dispatch details separately from listing status."],["Events and documents","Bring external updates and dispatch documents back into the operational context."]]},
 api:{eyebrow:"Full API suite",title:"Build connections around the work.",lead:"Connect your systems to the Prevayl platform with a full API suite spanning orders, shipments, customers, carriers, quotes and invoices.",label:"API suite",sub:"Your systems. Connected to the operating record.",points:[["Business records","Connect the customer, vehicle movement and financial context your workflow needs."],["Workflow integration","Design connections around record changes, handoffs and the next operational action."],["Implementation support","Work with our team on the supported endpoints, authentication, mappings and access for your integration."]]},
 "vtims-edi":{eyebrow:"In-house EDI • VTIMS connection",title:"Speak the language of vehicle logistics.",lead:"Prevayl’s in-house EDI supports VTIMS connection work, bringing structured trading-partner messages into the same platform that runs your vehicle movements.",label:"VTIMS + EDI",sub:"Structured exchange. Operational context.",points:[["In-house EDI engine","An X12 parser, transaction generators and direct AS2 transport keep the integration work within the Prevayl stack."],["Shipment-centered exchange","Connect tender information, responses and shipment status with vehicle logistics workflows."],["Partner-specific setup","Align partner identifiers, message maps, credentials and acceptance testing to the VTIMS connection requirements."]]}
};
const resources=[
 {name:"Orders",fields:[["Record","DEMO-1042"],["Vehicles","2 VINs"],["Customer","Example Motors"]],description:"Keep vehicle, location and customer information connected to one order."},
 {name:"Shipments",fields:[["Movement","Detroit → Nashville"],["Milestone","Pickup recorded"],["Next event","Delivery update"]],description:"Connect movement details and shipment milestones to the systems that need them."},
 {name:"Customers",fields:[["Account","Example Motors"],["Location","Receiving facility"],["Context","Order relationship"]],description:"Link the customer record and operating context across your tools."},
 {name:"Carriers",fields:[["Carrier","Example Transport"],["Equipment","Open car hauler"],["Context","Assignment record"]],description:"Connect the carrier relationship and shipment assignment context."},
 {name:"Quotes",fields:[["Request","Vehicle movement"],["Lane","Detroit → Nashville"],["Decision","Review quote"]],description:"Connect quote requests with the lane, vehicle and commercial context."},
 {name:"Invoices",fields:[["Document","INV-DEMO-1042"],["Order","DEMO-1042"],["State","Review for billing"]],description:"Link billing records to the work that created the obligation."}
];
function DispatchVisual(){const [tab,setTab]=useState(0);const states=[["Listing","Published listing","Marketplace visibility"],["Dispatch","Carrier commitment","Fulfillment record"],["Documents","Shipment paperwork","Document connection"]];return <div className="ix-dispatch" aria-label="Illustrative Central Dispatch integration"><div className="ix-window"><span>PREVAYL / DISPATCH DESK</span><b>WORKFLOW EXAMPLE</b></div><div className="ix-dual"><article><small>ORDER WORKSPACE</small><h3>DEMO-1042</h3><div className="ix-lane"><i/>Detroit, MI<span>↓</span><i/>Nashville, TN</div><div className="ix-vehicles"><img src="/vehicle-vectors/sedan.svg" alt="Sedan side profile"/><img src="/vehicle-vectors/suv.svg" alt="SUV side profile"/></div><footer>2 vehicles • Open transport</footer></article><div className="ix-bridge" aria-hidden="true"><span>ORDER LINK</span><b>⇄</b><i/><i/><i/></div><article className="ix-market"><small>CENTRAL DISPATCH</small><h3>{states[tab][1]}</h3><div className="ix-linked"><span>External reference</span><strong>LINKED TO DEMO-1042</strong></div><div className="ix-signal"><i/>{states[tab][2]}</div><p>{tab===0?"Keep listing changes tied to the original shipment.":tab===1?"Check carrier acceptance independently from the listing.":"Connect dispatch sheets and available shipment documents."}</p></article></div><div className="ix-tabs" role="group" aria-label="Explore the Central Dispatch connection">{states.map((s,i)=><button key={s[0]} aria-pressed={tab===i} onClick={()=>setTab(i)}>{s[0]}<span>↗</span></button>)}</div><p className="ix-note">Illustrative linked records. This demonstration does not post, book or send anything.</p></div>}
function ApiVisual(){const [active,setActive]=useState(0);const item=resources[active];return <div className="ix-api"><div className="ix-window"><span>PREVAYL / API SUITE</span><b>RESOURCE EXPLORER</b></div><div className="ix-api-body"><div className="ix-resource-list" role="group" aria-label="Explore API resources">{resources.map((r,i)=><button key={r.name} aria-pressed={active===i} onClick={()=>setActive(i)}><span>0{i+1}</span>{r.name}<b>↗</b></button>)}</div><div className="ix-payload" aria-live="polite"><div><small>ILLUSTRATIVE DATA VIEW</small><strong>{item.name}</strong></div><dl>{item.fields.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p>{item.description}</p><footer><span>YOUR SYSTEM</span><b>⇄</b><span>PREVAYL</span></footer></div></div><p className="ix-note">A resource overview, not executable API documentation. Endpoint access and supported operations are scoped during integration setup.</p></div>}
function EdiVisual(){const [active,setActive]=useState(0);const docs=[{id:"204",name:"Load tender",direction:"INBOUND",text:"Receive structured tender information for the vehicle movement.",lines:["Trading partner reference","Vehicle and shipment details","Pickup and delivery stops"]},{id:"990",name:"Tender response",direction:"OUTBOUND",text:"Return the acceptance or rejection decision for a tender.",lines:["Original shipment reference","Response decision","Transaction control number"]},{id:"214",name:"Shipment status",direction:"OUTBOUND",text:"Translate movement milestones into a structured status message.",lines:["Shipment identification","Milestone and event time","Location context"]},{id:"997",name:"Acknowledgment",direction:"EXCHANGE CONTROL",text:"Keep message acknowledgment distinct from completing the transport job.",lines:["Interchange reference","Transaction acknowledgment","Processing outcome"]}];const d=docs[active];return <div className="ix-edi"><div className="ix-window"><span>IN-HOUSE EDI / VTIMS CONNECTION</span><b>X12 + AS2</b></div><div className="ix-edi-body"><div className="ix-envelope"><span>TRADING-PARTNER EXCHANGE</span><div className="ix-paper"><header><strong>{d.id}</strong><div><small>{d.direction}</small><h3>{d.name}</h3></div></header>{d.lines.map((l,i)=><div className="ix-segment" key={l}><b>0{i+1}</b><span>{l}</span><i/></div>)}<footer>Illustrative message contents</footer></div></div><aside><small>PREVAYL EDI ENGINE</small><div className="ix-edi-core">EDI<span>IN-HOUSE</span></div><p>{d.text}</p><div className="ix-engine-tags"><span>Parse & map</span><span>Control numbers</span><span>Retry handling</span></div></aside></div><div className="ix-tabs" role="group" aria-label="Explore EDI transaction types">{docs.map((r,i)=><button key={r.id} aria-pressed={active===i} onClick={()=>setActive(i)}><strong>{r.id}</strong>{r.name}</button>)}</div><p className="ix-note">Engine transaction examples. The enabled VTIMS message set and partner mapping are confirmed during connection setup and testing.</p></div>}
export function IntegrationOverview(){return <section className="pvl-wrap pvl-section ix-overview"><div className="pvl-section-heading"><div><p className="pvl-eyebrow">Connected beyond the console</p><h2>The connections<br/>that move the operation.</h2></div><p>Central Dispatch integration. A full API suite. In-house EDI for VTIMS connection. Prevayl connects the dispatch desk with the wider vehicle logistics ecosystem.</p></div><div className="ix-overview-grid">{(Object.keys(data) as IntegrationKind[]).map((key,i)=><Link href={"/platform/integrations/"+key+"/"} key={key} className={"ix-overview-card ix-overview-"+key}><div className="ix-cover" aria-hidden="true">{i===0?<><span>PREVAYL</span><b>⇄</b><span>CENTRAL<br/>DISPATCH</span></>:i===1?<><b>{"{ }"}</b><div>{["Orders","Carriers","Invoices"].map(s=><span key={s}>{s}<i>↗</i></span>)}</div></>:<><b>EDI</b><div><span>204 →</span><span>← 990</span><span>← 214</span></div><strong>VTIMS</strong></>}</div><small>{data[key].eyebrow}</small><h3>{data[key].label}</h3><p>{data[key].sub}</p><span className="pvl-text-link">Explore the connection ↗</span></Link>)}</div></section>}
export function IntegrationPage({kind}:{kind:IntegrationKind}){const d=data[kind];return <main className="pvl-redesign"><PageHero eyebrow={d.eyebrow} title={d.title} lead={d.lead} primaryCta={{href:"/contact?type=sales",label:"Discuss your integration"}} secondaryCta={{href:"#connection",label:"Explore the connection"}}/><section id="connection" className="pvl-wrap pvl-section">{kind==="central-dispatch"?<DispatchVisual/>:kind==="api"?<ApiVisual/>:<EdiVisual/>}</section><section className="pvl-wrap pvl-section"><div className="pvl-section-heading"><div><p className="pvl-eyebrow">Built into the workflow</p><h2>{kind==="central-dispatch"?"From listing to handoff.":kind==="api"?"Your data has a job to do.":"Messages that mean something."}</h2></div><p>{kind==="central-dispatch"?"Keep marketplace activity connected to the record your team already uses.":kind==="api"?"Build around the records, permissions and business outcomes your operation needs.":"Make the trading-partner exchange part of the vehicle movement, with a clear place for the next operational decision."}</p></div><div className="ix-capabilities">{d.points.map(([h,p],i)=><article key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></article>)}</div></section><section className="pvl-wrap pvl-section ix-setup"><p className="pvl-eyebrow">Connection planning</p><h2>Bring your systems.<br/>We’ll work through the connection.</h2><p>{kind==="central-dispatch"?"We’ll review your Central Dispatch account access, enabled API capabilities and the listing, dispatch and document workflows you need.":kind==="api"?"Bring the source and destination systems, the records you need to exchange and the actions you want to automate. We’ll confirm the supported API contract and access requirements.":"Bring the VTIMS trading-partner requirements, message specifications and connection contacts. We’ll work through the mapping, transport configuration and partner acceptance process."}</p>{kind==="central-dispatch"&&<p className="ix-note">Central Dispatch API availability depends on your account and enabled services. <a href="https://www.centraldispatch.com/features/api" target="_blank" rel="noreferrer">Review Central Dispatch’s API overview ↗</a></p>}<Link className="pvl-button" href="/contact?type=sales">Contact Sales ↗</Link></section><IntegrationOverview/><CTA title="Connect the systems behind the movement." primary={{href:"/contact?type=sales",label:"Contact Sales"}}/></main>}
