"use client";
import {useState} from "react";
const roles=[
{name:"COO",tag:"The whole operation",question:"Where does the business need my attention?",answer:"Start with margin exposure, then review open receivables and loads that need a decision.",kind:"finance",metrics:[["Revenue · USD","$84,200"],["Gross margin","23.8%"],["Needs attention","3 loads"]],rows:[["Revenue","84200"],["Carrier cost","64160"],["Gross profit","20040"]],title:"An operating picture you can act on.",sources:["Orders","Financial summaries","Customer analytics"]},
{name:"Dispatch",tag:"Every load. Next move.",question:"What should I work on next?",answer:"Review the unassigned Detroit load first. Compare eligible carriers and the recorded rate position before proposing a match.",kind:"route",metrics:[["Shipment","DEMO-1042"],["Route","MI → TN"],["Stage","Carrier review"]],rows:[["Detroit, MI","Pickup"],["Carrier shortlist","Review"],["Nashville, TN","Delivery"]],title:"The next move, with the context attached.",sources:["Shipment details","Carrier performance","Lane pricing"]},
{name:"Sales",tag:"The next conversation",question:"What should I know before this customer call?",answer:"Review the open quote, recent shipment history and outstanding balance together before following up.",kind:"pipeline",metrics:[["Customer","Demo Motors"],["Open quote","$1,250"],["Stage","Follow-up"]],rows:[["Customer context","Ready"],["Lane & quote","Review"],["Follow-up","Next"]],title:"Walk into the conversation informed.",sources:["Customer history","Quote pipeline","Receivables"]},
{name:"Accounting",tag:"Follow the money",question:"Which balances need a closer look?",answer:"Review the overdue customer invoices. Carrier payables remain a separate obligation with their own terms and status.",kind:"finance",metrics:[["Receivables","$18,450"],["Carrier payables","$12,200"],["Overdue","$4,800"]],rows:[["Current AR","13650"],["Overdue AR","4800"],["Carrier AP","12200"]],title:"A clear view of both sides of the ledger.",sources:["Invoices","AR / AP","Carrier settlements"]},
{name:"Management",tag:"See the exceptions",question:"How is the operation performing?",answer:"Compare delivery activity with outstanding exceptions, then drill into the loads behind the numbers.",kind:"performance",metrics:[["Delivered","42"],["In movement","18"],["Exceptions","3"]],rows:[["Mon","6"],["Tue","9"],["Wed","7"],["Thu","12"],["Fri","8"]],title:"See the pattern. Find the exception.",sources:["Load activity","Fleet performance","Profitability"]},
{name:"Carrier",tag:"Company movement",question:"Which awarded load still needs a driver?",answer:"Review the Detroit pickup and available drivers. Compare preferred lanes before proposing an assignment.",kind:"route",metrics:[["Awarded load","DEMO-1042"],["Assignment","Review"],["Pickup","Detroit"]],rows:[["Awarded","Load ready"],["Driver availability","Compare"],["Assignment","Propose"]],title:"Connect awarded work with available capacity.",sources:["Company loads","Driver availability","Settlements"]},
{name:"Driver",tag:"Your next pickup",question:"What do I need for my next pickup?",answer:"Check the pickup window and load instructions, then review the required documents before arrival.",kind:"journey",metrics:[["Next stop","Detroit, MI"],["Window","9–11 AM"],["Vehicle","1 SUV"]],rows:[["Pickup details","Review"],["Load documents","Check"],["Arrival & handoff","Next"]],title:"The important details, close at hand.",sources:["Own loads","Pickup details","Load documents"]},
{name:"Viewer",tag:"Look up. Understand.",question:"Where is this shipment in the process?",answer:"The example load is in transit. Review its recorded milestones and delivery window for the latest context.",kind:"journey",metrics:[["Shipment","DEMO-1042"],["Status","In transit"],["Next","Delivery"]],rows:[["Order created","Recorded"],["Picked up","Recorded"],["Delivery","Upcoming"]],title:"A useful answer starts with the record.",sources:["Shipment status","Customer context","Platform activity"]}
];
function EvidenceVisual({role}:{role:typeof roles[number]}){
if(role.kind==="finance"){const max=Math.max(...role.rows.map(r=>Number(r[1])));return <div className="rx-bars">{role.rows.map(([label,value],i)=><div key={label}><div><span>{label}</span><strong>{Number(value).toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0})}</strong></div><div className="rx-bar-track"><i style={{width:(Number(value)/max*100)+"%",opacity:i===1?.5:1}}/></div></div>)}</div>}
if(role.kind==="performance")return <div className="rx-chart" aria-label="Illustrative delivered loads: Monday 6, Tuesday 9, Wednesday 7, Thursday 12, Friday 8">{role.rows.map(([day,value])=><div key={day}><strong>{value}</strong><i style={{height:Number(value)*10}}/><span>{day}</span></div>)}</div>;
if(role.kind==="route")return <div className="rx-route"><div className="rx-route-grid" aria-hidden="true"><svg viewBox="0 0 600 150"><path d="M30 100 L130 100 L210 45 L330 45 L420 105 L565 105" fill="none" stroke="#C9A84C" strokeWidth="3" strokeDasharray="7 6"/><circle cx="30" cy="100" r="8" fill="#C9A84C"/><circle cx="330" cy="45" r="9" fill="#0C1118" stroke="#C9A84C" strokeWidth="3"/><circle cx="565" cy="105" r="8" fill="#A8C4D8"/></svg></div><div className="rx-route-labels">{role.rows.map(([a,b])=><div key={a}><strong>{a}</strong><span>{b}</span></div>)}</div></div>;
return <div className={"rx-journey "+(role.kind==="pipeline"?"rx-pipeline":"")}>{role.rows.map(([a,b],i)=><div key={a}><span className="rx-step">{i<2?"✓":"03"}</span><div><strong>{a}</strong><span>{b}</span></div>{i===2&&<b aria-hidden="true">↗</b>}</div>)}</div>;
}
export function Roles(){
const [active,setActive]=useState(0);const r=roles[active];
return <><section className="pvl-wrap pvl-section rx-section" id="role-workspaces"><div className="rx-heading"><div><p className="pvl-eyebrow">One intelligence layer / Eight working perspectives</p><h2>Choose the role.<br/><em>See the work.</em></h2></div><p>Explore the questions, records and decisions that matter to each team. The assistant’s context changes with the job.</p></div>
<div className="rx-tabs" aria-label="Explore assistant roles">{roles.map((role,i)=><button key={role.name} onClick={()=>setActive(i)} aria-pressed={i===active} aria-controls="role-workspace"><span className="rx-role-index">{String(i+1).padStart(2,"0")}</span><strong>{role.name}</strong><span className="rx-role-tag">{role.tag}</span></button>)}</div>
<div className="rx-workspace" id="role-workspace"><div className="rx-window"><div><span className="rx-spark">✦</span> PREVAYL <span className="rx-window-role">/ {r.name} Assistant</span></div><span className="rx-example">ILLUSTRATIVE WORKSPACE · SAMPLE DATA</span></div>
<div className="rx-workspace-body"><div className="rx-evidence"><div className="rx-evidence-heading"><span className="pvl-eyebrow">Your working context</span><span className="rx-context-dot">Connected records</span></div><h3>{r.title}</h3><div className="rx-metrics">{r.metrics.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><EvidenceVisual role={r}/><div className="rx-sources"><span>Context</span>{r.sources.map(s=><span key={s}>{s}</span>)}</div></div>
<div className="rx-conversation" aria-live="polite"><span className="pvl-eyebrow">A question becomes a next step</span><div className="rx-question">{r.question}<span>You</span></div><div className="rx-answer"><div><span className="rx-spark">✦</span><strong>{r.name} Assistant</strong></div><p>{r.answer}</p><div className="rx-reference"><span>↳</span> {r.sources[0]} <span>·</span> {r.sources[1]}</div></div><div className="rx-decision"><span>Next step</span><strong>{active===7?"Inspect the shipment record":"Review the supporting records"} <span aria-hidden="true">↗</span></strong></div></div></div></div>
<p className="tech-note">Illustrative examples explain the role contexts; they are not live answers or performance results. The actual deployed COO Assistant is shown above. Available data and actions depend on account permissions.</p></section>
<section className="pvl-wrap pvl-section rx-connected"><div className="rx-heading"><div><p className="pvl-eyebrow">From context to decision</p><h2>An answer with<br/><em>something behind it.</em></h2></div><p>The useful part of an assistant is what it brings into the conversation: the order, the customer, the money and the next operational decision.</p></div><div className="rx-process"><article><div className="rx-record-stack"><span>ORDERS <b>DEMO-1042</b></span><span>CUSTOMER <b>Demo Motors</b></span><span>FINANCE <b>Invoice context</b></span></div><p className="pvl-eyebrow">01 / Context</p><h3>Start with the record.</h3><p>Bring the relevant load, customer and financial context into the question.</p></article><article><div className="rx-context-wheel"><span>Role</span><b>✦</b><span>Question</span><small>Relevant platform tools</small></div><p className="pvl-eyebrow">02 / Perspective</p><h3>Work through the right lens.</h3><p>The role shapes the assistant’s focus—from personal load details to the broader operation.</p></article><article><div className="rx-outcome"><span>REVIEW</span><strong>Supporting records</strong><div><i/> Understand the situation</div><div><i/> Review the next step</div></div><p className="pvl-eyebrow">03 / Decision</p><h3>Make the next move clearer.</h3><p>Use the answer to investigate, follow up or review a proposed action in the appropriate workflow.</p></article></div></section></>;
}

