"use client";
import {FleetWorkspace} from "./FleetWorkspace";
import {SolutionWorkspace} from "./SolutionWorkspace";
import {PlatformVisual} from "./PlatformVisual";
import {useState} from "react";
import {VisualContext} from "./VisualContext";
import {VisualIcon} from "./VisualExamples";
import {visualFor,type VisualKind} from "@/content/section-visuals";
type Spec={label:string;focus:string[];detail:string[]};
const specs:Record<VisualKind,Spec>={
board:{label:"Order workspace",focus:["The vehicle","The movement","The exception"],detail:["Keep the VIN and customer tied to the same order.","Follow pickup, carrier assignment and delivery in context.","Focus the next decision on the load that needs attention."]},
match:{label:"Carrier shortlist",focus:["Lane experience","Equipment fit","Review the carrier"],detail:["Compare relevant lane history before choosing a carrier.","Check the equipment against the vehicles being moved.","Review the carrier record and the proposed assignment together."]},
documents:{label:"Document review",focus:["On the record","Expiry context","Decision trail"],detail:["Bring carrier and shipment documents into the work.","A document on file still needs its dates and coverage reviewed.","Keep the reason for a decision close to its supporting information."]},
ledger:{label:"Transaction workspace",focus:["Customer invoice","Carrier payable","Reconciliation"],detail:["Track the amount billed to the customer.","Track the carrier obligation separately from customer payment.","Investigate differences using the underlying transaction records."]},
trend:{label:"Operational performance",focus:["Volume","Margin","Exceptions"],detail:["Compare movement activity across the reporting period.","Read gross profit alongside revenue and carrier cost.","Drill into the orders behind an unusual result."]},
forecast:{label:"Volume outlook",focus:["Recorded volume","Current pace","Planning context"],detail:["Start with movements already recorded this month.","Compare the current pace with the rest of the period.","Use projections as context, with their assumptions visible."]},
route:{label:"Lane & stop sequence",focus:["Pickup","Route context","Delivery"],detail:["Start with the pickup location and time window.","Review stop sequence, distance and operational constraints.","Bring the receiving location and delivery window into the plan."]},
capacity:{label:"Load configuration",focus:["Vehicle mix","Deck positions","Review the fit"],detail:["A sedan, SUV and pickup have different space requirements.","Arrange vehicles against the equipment’s available positions.","Review vehicle dimensions, weight and operability before committing."]},
portal:{label:"Customer portal",focus:["Your brand","Their vehicles","Next handoff"],detail:["Give the customer a familiar branded workspace.","Keep each vehicle’s current shipment status visible.","Connect the delivery window with its receiving details and documents."]},
connections:{label:"Connected workflow",focus:["Source information","Shared record","Next system"],detail:["Bring the relevant information into the workflow.","Connect the source data to its shipment, customer or financial record.","Review each enabled integration and its result."]},
permissions:{label:"Role & workspace",focus:["People","Working context","Action scope"],detail:["Start with the person and their organization.","Identify the workspace and information their job needs.","Review the permissions that apply to sensitive actions."]},
team:{label:"People behind the movement",focus:["Operations","Customer relationships","Product"],detail:["The daily work of coordinating vehicles and carriers.","The conversations that connect a service to a customer’s needs.","Turn operational feedback into a clearer working experience."]},
principles:{label:"How the work improves",focus:["Track","Measure","Improve"],detail:["Make the work and its outcomes visible.","Use the evidence to understand the problem.","Apply what is learned to the next repeatable workflow."]},
message:{label:"A useful conversation",focus:["Context","The message","Next step"],detail:["Bring the order, lane or question into the conversation.","Make the reason for the update clear.","Give the recipient a concrete point to review or follow up."]},
pricing:{label:"Economics of a movement",focus:["Customer price","Carrier cost","Margin"],detail:["Review the price quoted for the vehicle movement.","Bring the expected carrier cost into the decision.","Understand what remains after the costs in the example."]},
onboarding:{label:"From introduction to first load",focus:["Your operation","Your setup","First workflow"],detail:["Start with your lanes, team and monthly vehicle volume.","Review data, integrations and role requirements.","Walk through the first order and the handoffs around it."]},
library:{label:"A guide to the work",focus:["Get started","Run the operation","Connect the tools"],detail:["Find the account and first-load guidance.","Explore dispatch, accounting and carrier documentation.","Read the integration documentation and its availability notes."]},
inspection:{label:"Vehicle evidence record",focus:["Vehicle condition","Handoff details","Documents"],detail:["Connect inspection details to the vehicle being moved.","Keep pickup and delivery context with the movement.","Review the evidence supporting the shipment’s document trail."]},
automation:{label:"Event → context → next action",focus:["Trigger","Evaluate","Review"],detail:["An order event or schedule starts the workflow.","Bring the relevant records and configured thresholds into the decision.","Inspect the proposed action and the account’s execution settings."]},
pin:{label:"Handoff authorization",focus:["Driver request","Context checks","Decision"],detail:["Connect the request to the booked carrier and shipment.","Review location, timing and recorded carrier information.","Inspect the recommendation before the applicable authorization step."]}
};
function Graphic({kind,active=0}:{kind:VisualKind;active?:number}){
if(kind==="ledger"||kind==="pricing")return <div className="sx-finance"><div className="sx-finance-top"><span>DEMO-1042</span><span>USD</span></div><div className="sx-finance-values"><div><small>{kind==="ledger"?"Customer invoice":"Customer price"}</small><strong>$1,250</strong></div><span>→</span><div><small>{kind==="ledger"?"Carrier payable":"Carrier cost"}</small><strong>$950</strong></div></div><div className="sx-finance-track"><i/><b/></div><div className="sx-finance-bottom"><span>{kind==="ledger"?"Separate obligations":"Before other costs"}</span><strong>{kind==="ledger"?"Review each status":"$300 · 24% gross margin"}</strong></div><div className="sx-ledger-rows"><span>Order record</span><span>Charge details</span><span>Payment context</span></div></div>;
if(kind==="trend"||kind==="forecast")return <div className="sx-trend"><div className="sx-chart-title"><span>{kind==="forecast"?"Month-to-date + outlook":"Example delivered vehicles"}</span><strong>{kind==="forecast"?"PACE VIEW":"42"}</strong></div><div className="sx-columns" role="img" aria-label="Illustrative series of six values, 4, 6, 5, 8, 9, 10">{[4,6,5,8,9,10].map((n,i)=><div key={i}><span>{n}</span><i className={kind==="forecast"&&i>3?"projected":""} style={{height:n*9}}/><small>{kind==="forecast"?"W"+(i+1):["Mon","Tue","Wed","Thu","Fri","Sat"][i]}</small></div>)}</div>{kind==="forecast"&&<p className="sx-caption">Solid: recorded example · Dashed: illustrative outlook</p>}</div>;
if(kind==="route")return <div className="sx-route"><div className="sx-route-map"><svg viewBox="0 0 600 200" aria-hidden="true"><path d="M0 70h180l70 75h200l150-60M70 0v80l80 120M310 0v75l100 125M0 175l600-130" stroke="#2E4057" strokeWidth="1" fill="none"/><path d="M60 140L180 140L270 70L410 70L540 125" stroke="#C9A84C" strokeWidth="4" strokeDasharray="8 5" fill="none"/>{[[60,140],[270,70],[540,125]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="17" fill="#0C1118" stroke={active===i?"#F0F4F8":"#C9A84C"} strokeWidth="2"/><text x={x} y={y+5} textAnchor="middle" fontSize="13" fill="#F0F4F8">{i+1}</text></g>)}</svg></div><div className="sx-route-labels"><span>Detroit, MI<small>Pickup</small></span><span>Lane context<small>Review stops</small></span><span>Nashville, TN<small>Delivery</small></span></div></div>;
if(kind==="capacity")return <div className="sx-capacity"><div className="sx-equipment"><span>TRANSPORTER / DECK PLAN</span><strong>Vehicle fit review</strong></div>{[["Sedan","SUV","Sedan"],["Pickup","SUV","Reserve"]].map((deck,i)=><div className="sx-deck" key={i}><small>{i?"LOWER":"UPPER"}</small>{deck.map((v,j)=><div key={j} className={v==="Reserve"?"reserve":""}><VisualIcon name="truck"/><strong>{v}</strong></div>)}</div>)}<div className="sx-ledger-rows"><span>Dimensions</span><span>Weight</span><span>Operability</span></div></div>;
if(kind==="match")return <div className="sx-ranks">{[["Example Carrier A","Lane history",92],["Example Carrier B","Equipment fit",84],["Example Carrier C","Available capacity",76]].map(([name,why,score],i)=><div key={name} className={active===i?"selected":""}><span>0{i+1}</span><div><strong>{name}</strong><small>{why}</small><i style={{width:score+"%"}}/></div><b>{score}<small>example</small></b></div>)}</div>;
if(kind==="board"||kind==="portal")return <div className="sx-board">{kind==="portal"&&<div className="sx-portal-brand"><span>YOUR BRAND</span><strong>Vehicle movements</strong></div>}<div className="sx-board-head"><span>VEHICLE</span><span>LANE</span><span>STATUS</span></div>{[["SUV · 1042","Detroit → Nashville","In transit"],["Sedan · 1043","Tampa → Atlanta","Pickup"],["Pickup · 1045","Chicago → Denver","Review"]].map(([v,l,s],i)=><div className={active===i?"selected":""} key={v}><span><VisualIcon name="truck"/>{v}</span><span>{l}</span><b>{s}</b></div>)}</div>;
if(kind==="inspection"||kind==="documents"||kind==="pin")return <div className="sx-proof"><div className="sx-proof-symbol"><VisualIcon name={kind==="pin"?"shield":"document"}/><span>{kind==="pin"?"HANDOFF REVIEW":kind==="inspection"?"VEHICLE RECORD":"DOCUMENT FILE"}</span><strong>DEMO-1042</strong></div><div className="sx-proof-list">{(kind==="pin"?["Carrier identity","Pickup location","Authorization decision"]:kind==="inspection"?["Pickup condition","Delivery condition","eBOL & signatures"]:["Authority record","Insurance dates","Supporting documents"]).map((s,i)=><div className={i===active?"selected":""} key={s}><i>{i+1}</i><strong>{s}</strong><small>{kind==="pin"?"Review":"On the record"}</small></div>)}</div></div>;
if(kind==="message")return <div className="sx-message"><div><span>PREVAYL</span><small>Example conversation</small></div><p className="sx-message-q">What is the next step for this movement?</p><div className="sx-message-a"><span>✦</span><p>Review the current milestone, receiving details and documents attached to <strong>DEMO-1042</strong>.</p></div><div className="sx-message-context">Order context <span>→</span> Useful update <span>→</span> Follow-up</div></div>;
if(kind==="permissions"||kind==="team")return <div className="sx-team"><div className="sx-team-center"><VisualIcon name="people"/><strong>{kind==="team"?"PREVAYL":"WORKSPACE"}</strong><span>{kind==="team"?"People + operation":"Role context"}</span></div><div className="sx-team-roles">{(kind==="team"?["Operations","Customer relationships","Product"]:["Dispatcher","Accounting","Driver"]).map((s,i)=><div key={s} className={active===i?"selected":""}><i>{s.slice(0,1)}</i><span>{s}</span><small>{kind==="team"?"Connected work":"Review access"}</small></div>)}</div></div>;
if(kind==="library")return <div className="sx-library">{["FIRST LOAD","OPERATIONS","INTEGRATIONS"].map((s,i)=><div className={active===i?"selected":""} key={s}><span>0{i+1}</span><VisualIcon name={i===0?"document":i===1?"truck":"chart"}/><strong>{s}</strong><i/><i/><i/></div>)}</div>;
return null;
}
export function MiniVisual({kind}:{kind:VisualKind}){return <div className={"sx-mini sx-kind-"+kind} aria-label={specs[kind].label+" illustration"}><span className="sx-mini-label">ILLUSTRATION</span><VisualContext kind={kind}/></div>}
export function SectionVisual({slug="",index=0,title,kind,compact=false,showSecondary=false}:{slug?:string;index?:number;title?:string;kind?:VisualKind;compact?:boolean;showSecondary?:boolean}){
const chosen=kind??visualFor(slug,index);const spec=specs[chosen];const [active,setActive]=useState(0);if(!slug.startsWith("platform/")&&["automation","onboarding"].includes(chosen))return null;
if(slug === "solutions/carriers" || slug === "platform/carriers") return index < 4 ? <FleetWorkspace initial={(["builder","tracking","edi","finance"] as const)[index]} fixed/> : null;
return <div className={"sx-visual "+(compact?"sx-compact":"")} data-section-visual={chosen}><div className="sx-topline"><span><i/> {title||spec.label}</span><small>{/api|webhooks|zapier/.test(slug)?"PLANNED WORKFLOW · ILLUSTRATION":["team","principles","library","onboarding","connections","permissions"].includes(chosen)?"WORKFLOW ILLUSTRATION":"ILLUSTRATIVE WORKSPACE · SAMPLE DATA"}</small></div><div className="sx-body"><div className="sx-main">{slug.startsWith("platform/")?<PlatformVisual kind={chosen} title={title} slug={slug} index={index} active={active}/>:<SolutionWorkspace kind={chosen} title={title} slug={slug} index={index} active={active}/>}</div>{!compact&&<aside className="sx-inspector"><span className="sx-inspector-label">WHAT TO LOOK AT</span><div className="sx-focus" aria-label={"Explore "+(title||spec.label)}>{spec.focus.map((s,i)=><button key={s} onClick={()=>setActive(i)} aria-pressed={active===i}><span>0{i+1}</span>{s}<b>↗</b></button>)}</div><p aria-live="polite">{spec.detail[active]}</p></aside>}</div></div>
}
