import type {ReactNode} from "react";
import type {VisualKind} from "@/content/section-visuals";
import {PlatformVisual} from "./PlatformVisual";
type Props={slug:string;index:number;kind:VisualKind;active:number;title?:string};
function Frame({name,label,children}:{name:string;label:string;children:ReactNode}){return <div className="sw-workspace" data-solution-workspace={name}><header><span>{label}</span><b>SAMPLE WORKSPACE</b></header>{children}</div>}
function Rows({rows,active}:{rows:string[][];active:number}){return <div className="sw-rows">{rows.map(([a,b,c],i)=><div key={a} className={i===active?"sw-selected":""}><strong>{a}</strong><span>{b}</span><b>{c}</b></div>)}</div>}
function Dealer({index,active}:{index:number;active:number}){return index===0?<Frame name="dealer-inventory" label="DEMO MOTORS / INBOUND VEHICLES"><div className="sw-dealer-top"><span className="sw-brand">DM</span><div><small>YOUR DEALERSHIP WORKSPACE</small><h4>Know what is arriving.</h4></div><b>3 VINs</b></div><div className="sw-inventory">{[["Sedan","VIN ending 1042","Picked up","Detroit → Nashville"],["SUV","VIN ending 1043","Awaiting pickup","Tampa → Atlanta"],["Pickup","VIN ending 1045","Receiving review","Chicago → Denver"]].map(([a,b,c,d],i)=><article key={a} className={active===i?"sw-selected":""}><img className="sw-vehicle-vector" src={"/vehicle-vectors/"+["sedan","suv","pickup"][i]+".svg"} alt={a+" side-profile vehicle vector"} width="670" height="270" loading="lazy"/><h5>{a}</h5><small>{b}</small><span>{c}</span><p>{d}</p></article>)}</div><footer>Open a VIN to review its movement, contacts and documents.</footer></Frame>:<Frame name="dealer-delivery-packet" label="CUSTOMER SELF-SERVICE / DELIVERY PACKET"><div className="sw-packet"><div className="sw-paper"><span>eBOL / DEMO-1042</span><h4>Delivery record</h4><div className="sw-lines"><i/><i/><i/></div><b>Receiving acknowledgment</b><em>Signature record</em></div><div><h4>The answer is attached.</h4><Rows active={active} rows={[["Shipment update","Pickup recorded","Status"],["Receiving contact","Demo Motors","Contact"],["Delivery evidence","eBOL + condition record","Documents"]]}/></div></div><footer>Illustrative document packet. Availability follows the shipment and account configuration.</footer></Frame>}
const brokerRows=[
[["Pickup approaching","DEMO-1042 · No carrier","Dispatch review"],["Customer waiting","DEMO-1043 · Update due","Contact owner"],["Invoice outstanding","DEMO-1045 · Terms review","Accounting"]],
[["Dispatch","Carrier and pickup window","Movement"],["Customer team","Requirements and updates","Relationship"],["Accounting","Invoice and carrier payable","Money"]],
[["Example monthly volume","250 VINs","Usage"],["Agreed fee per VIN","Confirm your plan","Rate"],["Billing basis","Volume × agreed rate","Review"]],
[["Carrier identity","Name + linked identifiers","Compare"],["Coverage dates","Review effective and expiry","Documents"],["Assignment decision","Reviewer + recorded reason","History"]],
[["Carrier obligation","Order and agreed terms","Payable"],["Payment setup","Connected account status","Review"],["Transfer outcome","Recorded payment reference","Verify"]]
];
function Broker({index,active}:{index:number;active:number}){const names=["broker-exception-desk","broker-shared-order","broker-volume-billing","broker-carrier-review","broker-payment-tracker"];const labels=["EXCEPTION DESK","ONE ORDER / THREE RESPONSIBILITIES","PER-VIN BILLING WORKSHEET","ASSIGNMENT REVIEW","CARRIER PAYMENT FOLLOW-THROUGH"];return <Frame name={names[index]||names[0]} label={labels[index]||labels[0]}>{index===0?<div className="sw-exception-title"><b>03</b><div><h4>Work the exceptions.</h4><p>A named owner and a next decision for each open item.</p></div></div>:index===1?<div className="sw-record-strip"><b>DEMO-1042</b><span>Vehicle record</span><span>Detroit → Nashville</span><span>Customer + carrier</span></div>:index===2?<div className="sw-billing-equation"><strong>250<small>Example VINs</small></strong><b>×</b><strong>Agreed rate<small>From your plan</small></strong><b>=</b><strong>Usage charge<small>Before other fees</small></strong></div>:index===3?<div className="sw-license"><span>CARRIER RECORD</span><h4>Example Transport Co.</h4><p>Confirm the company behind the assignment.</p><b>Review required</b></div>:<div className="sw-transfer"><div><small>PAYABLE</small><strong>Carrier obligation</strong></div><span>↔</span><div><small>PAYMENT RECORD</small><strong>Evidence of transfer</strong></div></div>}<Rows rows={brokerRows[index]||brokerRows[0]} active={active}/><footer>{index===4?"Payment timing depends on the account, payment provider and applicable terms.":index===2?"This worksheet illustrates the billing basis; it is not a price quote.":"Illustrative operating record. Review the actual order before acting."}</footer></Frame>}
function Wholesale({index,active}:{index:number;active:number}){return <Frame name={["auction-import-review","auction-vin-register","auction-carrier-allocation","auction-condition-comparison"][index]} label={["AUCTION IMPORT / REVIEW BEFORE CREATION","VIN REGISTER / MULTIPLE SOURCES","ALLOCATION DESK","CONDITION RECORD / PICKUP & DELIVERY"][index]}>{index===0?<><div className="sw-import"><div><span>AUCTION FILE</span><h4>Inventory.csv</h4><p>Vehicle identifiers · Lot references · Locations</p></div><b>↘</b><div><span>IMPORT REVIEW</span><strong>2 ready · 1 needs attention</strong></div></div><Rows active={active} rows={[["VIN ending 1042","Pickup address present","Ready"],["VIN ending 1043","Vehicle details matched","Ready"],["VIN ending 1045","Receiving contact missing","Review"]]}/></>:index===1?<><h4>Every unit keeps its own history.</h4><Rows active={active} rows={[["VIN ending 1042","Auction A · Lot 081","Picked up"],["VIN ending 1043","Auction B · Lot 214","Assigned"],["VIN ending 1045","Auction A · Lot 093","Review"]]}/><div className="sw-register-key"><span>Source lot</span><span>Vehicle</span><span>Current movement</span><span>Document record</span></div></>:index===2?<><h4>Match the unit to the right movement.</h4><div className="sw-allocation">{[["Auction A","2 sedans","Example Carrier A"],["Auction B","1 SUV","Example Carrier B"]].map(([a,b,c],i)=><article key={a} className={i===active?"sw-selected":""}><span>{a}</span><strong>{b}</strong><div>Assigned movement</div><b>{c}</b><small>Receiving dealer on record</small></article>)}</div></>:<><div className="sw-condition">{["PICKUP","DELIVERY"].map((s,i)=><article key={s}><span>{s}</span><div className={"sw-condition-outline side-"+i}><i/><b/><em/></div><strong>{i?"Compare against pickup":"Record existing condition"}</strong><small>{i?"Note any discrepancy":"Attach photos to the VIN"}</small></article>)}</div><Rows active={active} rows={[["Vehicle reference","Same VIN at both handoffs","Match"],["Condition evidence","Separate pickup and delivery files","Compare"],["Acknowledgment","Receiving details and signature","Review"]]}/></>}<footer>Illustrative auction workflow; source availability depends on the configured integration.</footer></Frame>}
function Carrier({index,active}:{index:number;active:number}){return <Frame name={["carrier-trip-book","carrier-mobile-evidence","carrier-access-economics"][index]} label={["CARRIER OPERATIONS / ASSIGNED WORK","DRIVER / PICKUP EVIDENCE","CARRIER WORKSPACE / ACCESS"][index]}>{index===0?<><div className="sw-trip"><h4>The next load, ready to inspect.</h4><div><b>MI</b><span>Detroit pickup<br/>Contact + gate instructions</span><i>↗</i><b>TN</b><span>Nashville delivery<br/>Receiving window</span></div></div><Rows active={active} rows={[["Assigned movement","DEMO-1042 · Open transport","Review"],["Vehicle requirements","Keys + operability","Confirm"],["Trip record","Stops and shipment documents","On file"]]}/></>:index===1?<div className="sw-mobile"><div className="sw-mobile-device"><small>LOAD DEMO-1042</small><h4>Pickup evidence</h4><div className="sw-photo-grid">{["Front","Rear","Left","Right"].map(s=><span key={s}>＋<small>{s}</small></span>)}</div><b>Attach to this vehicle</b></div><div><h4>Capture where the work happens.</h4><Rows active={active} rows={[["Condition","Required views","Photos"],["Handoff","Releasing contact","Signature"],["Connection","Check sync outcome","Review"]]}/></div></div>:<><h4>See the work available to your team.</h4><div className="sw-access-list">{[["Drivers","Assigned loads and pickup detail"],["Operations","Company movements and assignments"],["Finance","Carrier settlement context"]].map(([a,b],i)=><div key={a} className={active===i?"sw-selected":""}><b>{a}</b><span>{b}</span></div>)}</div><p>Confirm the current access and commercial terms for your account.</p></>}<footer>Sample carrier workspace. Shipment and payment records remain separate.</footer></Frame>}
export function SolutionWorkspace(p:Props){if(p.slug==="solutions/dealers")return <Dealer index={p.index} active={p.active}/>;if(p.slug==="solutions/brokers")return <Broker index={p.index} active={p.active}/>;if(p.slug==="solutions/wholesale")return <Wholesale index={p.index} active={p.active}/>;if(p.slug==="solutions/carriers")return <Carrier index={p.index} active={p.active}/>;return <PlatformVisual {...p}/>;}

