import type {ReactNode} from "react";
import type {VisualKind} from "@/content/section-visuals";
function Box({name,children}:{name:string;children:ReactNode}){return <div className="uv-card" data-unique-visual={name}><div className="uv-label">ILLUSTRATIVE RECORD</div>{children}</div>}
export function SpecificVisual({title}:{title:string;kind?:VisualKind}){
if(title==="Account access and responsibilities")return <Box name="access-matrix"><h4>Access review worksheet</h4><table><thead><tr><th>Responsibility</th><th>Person</th><th>Review</th></tr></thead><tbody><tr><td>Organization admin</td><td>Account owner</td><td>Authentication</td></tr><tr><td>Daily dispatch</td><td>Operations</td><td>Assignment scope</td></tr><tr><td>Payment approval</td><td>Finance lead</td><td>Action limits</td></tr></tbody></table><p>Define who needs access, then confirm the actual permissions.</p></Box>;
if(title==="Data, integrations and retention")return <Box name="data-inventory"><h4>Know where the record goes.</h4><div className="uv-data"><div><b>ORDER RECORD</b><strong>Vehicle · Lane · Customer</strong><small>Identify the fields required by each connection.</small></div><dl><dt>Marketplace</dt><dd>Listing and carrier context</dd><dt>Accounting</dt><dd>Invoice and payment mapping</dd><dt>Customer portal</dt><dd>Authorized shipment visibility</dd><dt>Retention review</dt><dd>Discuss export and deletion needs</dd></dl></div></Box>;
if(title==="Automation and handoff controls")return <Box name="action-boundary"><h4>Prepared is different from executed.</h4><div className="uv-boundary"><article><span>PROPOSAL</span><strong>Release request</strong><p>Driver identity and pickup context attached.</p></article><b>Approval boundary</b><article><span>RECORDED RESULT</span><strong>Authorization decision</strong><p>Reviewer, decision and supporting checks.</p></article></div></Box>;
if(title==="Carrier match")return <Box name="carrier-identity"><h4>Compare both identities.</h4><div className="uv-pair"><div><small>BOOKED CARRIER</small><b>Example Transport</b><span>Carrier reference · A104</span></div><div><small>REQUESTING DRIVER</small><b>Linked company</b><span>Compare with A104</span></div></div><p>Name alone is not enough. Review the recorded association.</p></Box>;
if(title==="Pickup location")return <Box name="pickup-geofence"><div className="uv-geofence"><i/><i/><b>Pickup site</b><span>Driver request ●</span></div><dl className="uv-inline"><dt>Location result</dt><dd>Review distance</dd><dt>Shipment</dt><dd>DEMO-1042</dd></dl></Box>;
if(title==="Timing")return <Box name="pickup-window"><h4>Compare the request with the window.</h4><div className="uv-time"><span>08:00</span><span>10:00</span><span>12:00</span><span>14:00</span><i/><b>Pickup window</b><em>Request time</em></div><p>Scheduled window and request timestamp belong in the same review.</p></Box>;
if(title==="Carrier record")return <Box name="carrier-document-dates"><h4>Review the dates on file.</h4><div className="uv-file"><span>EXAMPLE CARRIER FILE</span><dl><dt>Insurance period</dt><dd>Effective / expiry</dd><dt>Authority record</dt><dd>Review current status</dd><dt>Blocked status</dt><dd>Check before release</dd></dl></div></Box>;
if(title==="Operating history")return <Box name="carrier-load-history"><h4>Previous work, visible.</h4><div className="uv-history">{[["DEMO-1018","Delivered","MI → TN"],["DEMO-1026","Delivered","OH → GA"],["DEMO-1042","Pickup review","MI → TN"]].map(([n,s,l])=><div key={n}><b>{n}</b><span>{l}</span><em>{s}</em></div>)}</div></Box>;
if(title==="Decision trail")return <Box name="authorization-log"><h4>The reasons travel with the decision.</h4><ol className="uv-log"><li><b>10:14</b><span>Driver request recorded<small>Shipment DEMO-1042</small></span></li><li><b>10:15</b><span>Context checks attached<small>Identity · Location · Timing</small></span></li><li><b>Pending</b><span>Dispatcher review<small>Decision and reviewer to be recorded</small></span></li></ol></Box>;
if(title==="Stage autonomy")return <Box name="autonomy-settings"><h4>Control each stage separately.</h4><div className="uv-switches">{[["Price","Propose"],["Post","Account policy"],["Book","Review authority"],["Handoff","Authorization"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div><p>Example configuration concepts, not live switches.</p></Box>;
if(title==="Recorded price position")return <Box name="negotiation-position"><h4>A rate with a boundary.</h4><div className="uv-price"><b>$950<small>Example carrier offer</small></b><div><span>Opening position</span><i/><span>Escalation line</span></div></div><p>Compare the offer with the stored negotiating position before responding.</p></Box>;
if(title==="Operational follow-through")return <Box name="follow-through-agenda"><h4>Follow-up has an owner.</h4><div className="uv-agenda"><div><b>PICKUP</b><span>Confirm the milestone</span></div><div><b>DELIVERY</b><span>Collect the signed POD</span></div><div><b>BILLING</b><span>Review invoice readiness</span></div></div></Box>;
return null;
}

