"use client";
import {PlatformVisual,PlatformTile} from "./PlatformVisual";
import {SectionVisual,MiniVisual} from "./SectionVisual";
import {featureVisual} from "@/content/section-visuals";

import {useState} from "react";
import Link from "next/link";
import {Screen} from "./Screen";
import {PageHero} from "../shared/PageHero";
import {CTA} from "./Shared";
import {Roles} from "./RoleWorkspaces";
export type TechMode="bots"|"dispatch"|"assistant"|"pin";
const stages=[
["Verify","VIN, vehicle, lane and dates","Decodes the vehicle, measures road miles and identifies missing order information before pricing.","Order details → verification result"],
["Price","A recorded negotiating position","Sets carrier pay against the posted margin, with negotiating room and an escalation line.","Customer price → carrier-pay position"],
["Post","Internal board + Central Dispatch","Prepares dispatcher and carrier notes and posts through the enabled marketplace connection.","Verified order → marketplace listing"],
["Evaluate","Carrier offers with context","Evaluates carrier eligibility and the recorded price position to accept, counter, decline or escalate.","Carrier offer → recommended response"],
["Negotiate","Room to move. A line to respect.","Uses rate steps and an aging clock at 36, 48 and 72 hours. Exceptions go to a person.","Unbooked load → revised position"],
["Book","A real carrier commitment","Connects carrier assignment, Central Dispatch dispatch creation and listing removal. This stage creates a contractual commitment.","Approved offer → carrier booking"],
["Handoff","PIN review at pickup","Checks the requesting carrier, pickup location, timing and carrier record before recommending authorization.","Driver request → handoff review"],
["Follow up","Keep the order moving","Supports pickup confirmation, slipped-pickup follow-up, proof-of-delivery collection and invoice chasing.","Milestone or delay → next action"]
];
const personas=[
["COO","Operational and financial visibility","Revenue by currency, profitability, settlements, customer analytics and operational metrics."],
["Dispatch","The load, the lane, the next move","Shipment lookups, carrier performance, driver availability, order legs and proposed assignments."],
["Sales","Customer context at the point of conversation","Customer history, quotes, pipeline, lane pricing context and outstanding receivables."],
["Accounting","The money behind the movement","AR, AP, invoice status, aging, carrier settlements and financial summaries."],
["Management","Performance across the operation","Load profitability, fleet performance, dispatch activity and settlement summaries."],
["Carrier","Company operations on the road","Company loads, driver assignments, expenses, revenue and settlement tracking."],
["Driver","A personal load companion","Own loads, pickup windows, route details, BOL access and personal pay summaries."],
["Viewer","Look up and understand","Read-oriented shipment, customer and activity assistance."]
];
const groups=[
{label:"Dispatch & movement",items:[["Margin Monitor","Flags shipments below the margin threshold."],["Dispatch Follow-up Tasks","Creates dispatcher follow-up tasks."],["Load Alert Bot","Texts carriers about matching loads."],["Order Status Bot","Texts customer shipment updates."],["Status Notifications","Raises in-app order-status notifications."],["BorderConnect Bot","Supports cross-border manifest filing."]]},
{label:"Revenue & accounting",items:[["Auto Invoice","Creates customer invoices and sends them by email."],["Invoice Chaser","Follows up on overdue invoices."],["Commission Booking","Books sales commission earnings."],["QuickBooks Sync","Pushes invoices into the connected ledger."],["Quick Pay Offer","Emails carrier settlement offers."],["Monthly Snapshot","Emails a monthly financial snapshot."]]},
{label:"Sales & relationships",items:[["Lead Qualifier","Scores and tags inbound leads."],["Quote Bot","Sends customer quote replies by text."],["Quote Follow-up","Emails customers about open quotes."],["Carrier Re-engagement","Reaches out to dormant carriers."],["Review Requester","Requests customer reviews after delivery."],["Customer Risk Scorer","Updates risk levels from invoice history."]]},
{label:"Oversight & intelligence",items:[["Carrier Monitor","Checks carrier records and creates alerts."],["Compliance Watcher","Checks compliance and produces an admin digest."],["Insurance Alerts","Emails carriers about lapsing coverage."],["Claims Escalation","Escalates claims and notifies involved parties."],["Rep Score Engine","Scores performance and raises warnings."],["Morning Briefing","Assembles the operations briefing."],["Health Report","Produces a platform health report."],["Bulk Classifier","Classifies imported records."],["Termination Reminder","Flags approaching contract termination."],["Breadcrumb Cleanup","Prunes stale tracking breadcrumbs."]]}
];
const config={
bots:{eyebrow:"Platform / AI Bots & Automations",title:"An operating team inside your operating system.",lead:"Specialist agents, event-driven workflows and an eight-stage dispatcher connect the work from first order to financial follow-through.",image:"workflow",screen:"AI workflow canvas",caption:"Deployed platform capture · September 7, 2026. Smart Order Pipeline is a populated draft; the AI Workflows dispatch switch is off in this capture. This is a configuration view, not a claim that the workflow is running."},
dispatch:{eyebrow:"Platform / AI Dispatch",title:"From a new order to the next decision.",lead:"Verify the load. Establish the rate. Work the market. Review the carrier. Follow the handoff. Dispatch intelligence reaches across the entire order, with autonomy configured stage by stage.",image:"dispatch",screen:"Dispatcher Bot — eight operational stages",caption:"Deployed Cars2Go settings · September 7, 2026. The Dispatcher Bot is shown ON with a mix of ACTS and PROPOSES stages. Stage settings determine which actions require a decision."},
assistant:{eyebrow:"Platform / Agentic AI Assistant",title:"Same platform. Intelligence for your role.",lead:"A dispatcher needs the next move. Accounting needs the money trail. A driver needs the next pickup. PREVAYL’s assistant brings a different working context to each role.",image:"assistant",screen:"Role-designated COO Assistant",caption:"Deployed assistant interface · September 7, 2026. This session displays COO Assistant. Explore the eight defined role contexts below."},
pin:{eyebrow:"Platform / PIN Protocol",title:"A controlled handoff for a high-value vehicle.",lead:"Connect driver authorization, pickup context and document release on the shipment record. The dispatch agent can review the request and surface the reasons behind its recommendation.",image:"pin",screen:"PIN Protocol — protected shipment",caption:"Deployed interface on an existing QA fixture · September 7, 2026. The screen shows the protected-load notice and PIN lock. No PIN was issued or released to create this capture. The request and its authorization stay connected to the shipment."}
};
function Flow(){const [active,setActive]=useState(0);return <section className="pvl-wrap pvl-section"><p className="pvl-eyebrow">Eight connected stages</p><h2>Intelligence follows the order.</h2><p className="pvl-section-lead">Explore the implemented dispatcher sequence. Each stage can propose or act according to the account’s policy and enabled integrations.</p><div className="tech-flow" aria-label="Dispatch stages">{stages.map((s,i)=><button key={s[0]} aria-pressed={active===i} onClick={()=>setActive(i)}><span>{String(i+1).padStart(2,"0")}</span><strong>{s[0]}</strong><small>{i===7?"Follow-through":"↓"}</small></button>)}</div><div className="tech-detail" aria-live="polite"><span className="tech-number">{String(active+1).padStart(2,"0")}</span><div><p className="pvl-eyebrow">{stages[active][0]}</p><h3>{stages[active][1]}</h3><PlatformVisual title={stages[active][1]} active={Math.min(active,2)} kind={active===0?"documents":active===1?"pricing":active===2?"board":active===3?"match":active===4?"pricing":active===5?"documents":active===6?"pin":"message"}/><p>{stages[active][2]}</p><div className="tech-signal">{stages[active][3]}</div></div></div></section>}
function Catalog(){const [active,setActive]=useState(0);return <section className="pvl-wrap pvl-section" id="automation-catalog"><p className="pvl-eyebrow">28 registered automation bots · 4 areas of work</p><h2>The detail is where the leverage lives.</h2><p className="pvl-section-lead">The deployed registry covers movement, finance, customer relationships and oversight. Registration describes available implementation—not the number enabled or successfully running in an account.</p><div className="tech-filters">{groups.map((g,i)=><button aria-pressed={active===i} key={g.label} onClick={()=>setActive(i)}>{g.label}</button>)}</div><div className="tech-catalog">{groups[active].items.map(([name,body],i)=><article key={name}><span className="pvl-eyebrow">{String(i+1).padStart(2,"0")} / {groups[active].label}</span><PlatformTile kind={featureVisual(name)} title={name}/><h3>{name}</h3><p>{body}</p></article>)}</div><p className="tech-note">Email, SMS, accounting and marketplace actions require the relevant setup. Some actions send real communications or change business records; enablement and approval are operational decisions.</p></section>}
function Pin(){return <section className="pvl-wrap pvl-section"><p className="pvl-eyebrow">Context before release</p><h2>A request carries more than a code.</h2><PlatformVisual kind="pin" title="The request and the release decision."/><div className="tech-catalog">{[["Carrier match","Links the requesting app user or verified driver link to the booked carrier."],["Pickup location","Uses the geofence result and distance recorded with the request."],["Timing","Compares the request with the scheduled pickup window."],["Carrier record","Checks recorded insurance and authority expiry, plus blocked status."],["Operating history","Adds completed-load history and available booking context."],["Decision trail","Records a recommendation and supporting checks for dispatch review."]].map(([h,t],i)=><article key={h}><span className="pvl-eyebrow">0{i+1} / Review context</span><PlatformTile title={h} kind={i===0?"permissions":i===1?"route":i===2?"board":i===3?"documents":i===4?"trend":"pin"}/><h3>{h}</h3><p>{t}</p></article>)}</div><div className="tech-signal">Driver request → context checks → authorization decision → completed handoff → document release</div><p className="tech-note">Handoff automation depends on the account’s stage policy and the quality of its carrier and pickup data. Dispatchers can inspect the recommendation before deciding.</p></section>}
export function TechExperience({mode}:{mode:TechMode}){const c=config[mode];return <main className="pvl-redesign"><PageHero eyebrow={c.eyebrow} title={c.title} lead={c.lead} primaryCta={{href:"#inside",label:"See inside the platform"}} secondaryCta={{href:"/contact?type=demo",label:"Book a walkthrough"}}/><div className="pvl-wrap tech-intro"><div><strong>8</strong><span>Dispatch stages</span></div><div><strong>8</strong><span>Assistant personas</span></div><div><strong>28</strong><span>Registered automation bots</span></div><div><strong>1</strong><span>Connected operating platform</span></div></div><section className="pvl-wrap pvl-section" id="inside"><div className="pvl-section-heading"><div><p className="pvl-eyebrow">Inside the deployed platform</p><h2>{mode==="bots"?"Real workflows. Visible decisions.":c.screen}</h2></div><p>Open the complete capture to inspect the interface. These are platform screens, with their actual configuration and status preserved.</p></div><Screen src={"/screenshots/live/"+c.image+".png"} title={c.screen} caption={c.caption} eager/></section>{mode==="pin"?<Pin/>:mode==="assistant"?<Roles/>:<Flow/>}{mode==="bots"&&<Catalog/>}{mode==="dispatch"&&<section className="pvl-wrap pvl-section"><p className="pvl-eyebrow">Decisions you can inspect</p><h2>Proposals, action limits and escalation.</h2><div className="tech-catalog">{[["Stage autonomy","Configure suggest or auto for each stage through the platform’s account policy."],["Recorded price position","Evaluate offers against the stored carrier-pay position and escalation line."],["Operational follow-through","Connect order milestones with pickup, POD and invoice follow-up."]].map(([h,t])=><article key={h}><PlatformTile title={h} kind={h==="Stage autonomy"?"permissions":h==="Recorded price position"?"pricing":"automation"}/><h3>{h}</h3><p>{t}</p></article>)}</div></section>}<section className="pvl-wrap pvl-section"><p className="pvl-eyebrow">Explore the intelligence layer</p><div className="tech-links">{[["/platform/agents","Automation team"],["/platform/dispatcher-bot","AI Dispatch"],["/platform/agentic-ai","Role-based assistants"],["/platform/pin-protocol","PIN Protocol"]].map(([href,label])=><Link key={href} href={href} className="sx-tech-link"><span>{label} ↗</span></Link>)}</div></section><CTA title="See the technology working in your operation." body="Walk through your roles, your integrations and the decisions you want the platform to handle."/></main>}



