import {VisualContext} from "./VisualContext";
import {featureVisual} from "@/content/section-visuals";
import type { ReactNode } from "react";

type IconName="truck"|"document"|"pin"|"chart"|"shield"|"people"|"message"|"clock";
const paths:Record<IconName,ReactNode>={
 truck:<><path d="M3 6h11v11H3zM14 10h4l3 4v3h-7"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></>,
 document:<><path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6M9 16h6"/></>,
 pin:<><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/></>,
 chart:<><path d="M4 3v17h17M8 16v-4M13 16V9M18 16V5"/><path d="m7 8 5-4 5 1"/></>,
 shield:<><path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6zM8 12l3 3 5-6"/></>,
 people:<><circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6M18 15c2 0 3 2 3 4v2"/></>,
 message:<><path d="M3 4h18v13H9l-6 4zM7 8h10M7 12h7"/></>,
 clock:<><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></>
};
export function VisualIcon({name}:{name:IconName}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}
function Frame({title,icon,children}:{title:string;icon:IconName;children:ReactNode}){return <article className="vx-card"><header><span className="vx-icon"><VisualIcon name={icon}/></span><h3>{title}</h3><span className="vx-example-label">EXAMPLE</span></header><div className="vx-card-body">{children}</div></article>}
function Tag({children,tone="gold"}:{children:ReactNode;tone?:"gold"|"blue"|"green"|"red"}){return <span className={"vx-tag "+tone}>{children}</span>}
function Lane(){return <div className="vx-lane"><div><small>Pickup</small><strong>Detroit, MI</strong></div><span aria-hidden="true">→</span><div><small>Delivery</small><strong>Nashville, TN</strong></div></div>}
function Attention(){return <Frame title="Know what needs attention" icon="clock"><div className="vx-table-label">NEXT ACTIONS <span>3 open</span></div><div className="vx-action"><i className="red">!</i><div><strong>DEMO-1045 <Tag tone="red">Review</Tag></strong><p>Carrier invoice needs review</p><small>Chicago → Denver</small></div><span>Today</span></div><div className="vx-action"><i>!</i><div><strong>DEMO-1043 <Tag>Pickup</Tag></strong><p>Confirm pickup with the carrier</p><small>Tampa → Atlanta</small></div><span>Today</span></div><div className="vx-action"><i className="blue">i</i><div><strong>DEMO-1042 <Tag tone="blue">In transit</Tag></strong><p>Update the delivery ETA</p><small>Detroit → Nashville</small></div><span>Tomorrow</span></div></Frame>}
function Margin(){return <Frame title="See the margin before you move" icon="chart"><Lane/><dl className="vx-ledger"><div><dt>Customer price</dt><dd>$1,250</dd></div><div><dt>Carrier pay</dt><dd>$950</dd></div><div><dt>Other costs</dt><dd>$50</dd></div><div className="vx-ledger-sub"><dt>Total cost</dt><dd>$1,000</dd></div><div className="vx-ledger-total"><dt>Margin <Tag>20%</Tag></dt><dd>$250</dd></div></dl><div className="vx-cost-bar" role="img" aria-label="Example: costs 80 percent, margin 20 percent"><span/><b/></div><div className="vx-chart-key"><span><i/> Cost</span><span><i/> Margin</span></div></Frame>}
function Movement(){return <Frame title="Every handoff stays in view" icon="pin"><Lane/><div className="vx-movement"><div className="done"><i><VisualIcon name="document"/></i><strong>Quoted</strong><small>Order details</small></div><div className="done"><i><VisualIcon name="truck"/></i><strong>Dispatched</strong><small>Carrier assigned</small></div><div className="current"><i><VisualIcon name="pin"/></i><strong>In transit</strong><small>Next: delivery</small></div><div><i><VisualIcon name="document"/></i><strong>Delivered</strong><small>Document review</small></div></div><div className="vx-inset"><span className="vx-dot"/><div><strong>The next handoff</strong><p>Confirm the receiving contact and delivery window.</p></div><Tag tone="blue">In transit</Tag></div></Frame>}
function Carrier(){return <Frame title="Put the carrier details together" icon="shield"><div className="vx-profile"><span className="vx-avatar"><VisualIcon name="truck"/></span><div><strong>Example Transport Co.</strong><p>Open transport · Midwest lanes</p></div></div><div className="vx-check-row"><span>Authority information</span><Tag tone="green">On file</Tag></div><div className="vx-check-row"><span>Insurance document</span><Tag tone="gold">Review expiry</Tag></div><div className="vx-check-row"><span>Lane history</span><Tag tone="blue">Available</Tag></div><div className="vx-check-row"><span>Assignment decision</span><Tag>Review required</Tag></div><p className="vx-footnote">A document on file is a starting point for review, not a compliance guarantee.</p></Frame>}
function Ranking(){return <Frame title="A shortlist with context" icon="people"><Lane/>{[["Example Carrier A","Lane experience","92"],["Example Carrier B","Equipment fit","84"],["Example Carrier C","Nearby capacity","76"]].map(([name,why,score],i)=><div className="vx-rank" key={name}><span>0{i+1}</span><div><strong>{name}</strong><p>{why}</p><div className="vx-rank-track"><i style={{width:score+"%"}}/></div></div><b>{score}<small>sample score</small></b></div>)}</Frame>}
function Money(){return <Frame title="Two sides of the transaction" icon="document"><div className="vx-money-sides"><div><small>Customer invoice</small><strong>$1,250</strong><Tag tone="green">Received</Tag></div><span aria-hidden="true">/</span><div><small>Carrier payable</small><strong>$950</strong><Tag>Due for review</Tag></div></div><div className="vx-inset"><span className="vx-icon"><VisualIcon name="shield"/></span><div><strong>Keep the obligations separate</strong><p>Customer payment and carrier payment are separate records to confirm.</p></div></div></Frame>}
function Message(){return <Frame title="An update with useful context" icon="message"><div className="vx-mail-meta"><span>To</span><strong>Example customer</strong><span>Subject</span><strong>Your vehicle has been picked up</strong></div><div className="vx-mail"><span className="vx-wordmark">PREVAYL</span><h4>Your vehicle is on its way.</h4><p>The pickup milestone is recorded for DEMO-1042.</p><Lane/><div className="vx-message-status"><span className="vx-dot"/> Pickup recorded <small>Example event</small></div></div></Frame>}
function PriceRange(){return <Frame title="Lane pricing context" icon="chart"><Lane/><div className="vx-price-range"><span className="vx-range-caption">ILLUSTRATIVE WORKING RANGE</span><div className="vx-range-values"><strong>$950</strong><span>$1,075</span><strong>$1,200</strong></div><div className="vx-range-band"><i/><b/><i/></div><div className="vx-range-values"><small>Lower bound</small><small>Midpoint</small><small>Upper bound</small></div></div><div className="vx-inset"><span className="vx-icon"><VisualIcon name="chart"/></span><div><strong>Check the history behind the rate</strong><p>Thin lane history deserves closer review before quoting.</p></div></div></Frame>}
function Trend(){return <Frame title="See what the lane is doing" icon="chart"><div className="vx-trend-heading"><div><small>Example gross margin</small><strong>20<span>%</span></strong></div><Tag tone="green">+4 points</Tag></div><div className="vx-bars" role="img" aria-label="Example monthly margins: January 16%, February 18%, March 17%, April 21%, May 19%, June 20%">{[16,18,17,21,19,20].map((v,i)=><div key={i}><strong>{v}%</strong><i style={{height:v*4+"px"}}/><small>{["Jan","Feb","Mar","Apr","May","Jun"][i]}</small></div>)}</div><p className="vx-footnote">Illustrative trend, not a live business metric.</p></Frame>}
const pairs:Record<string,[string,string]>={
 "home":["attention","margin"],"platform/dispatch":["attention","margin"],"platform/orders":["movement","attention"],"platform/accounting":["money","margin"],"platform/carriers":["carrier","ranking"],"platform/compliance":["carrier","movement"],"platform/ai":["ranking","margin"],"platform/agentic-ai":["attention","message"],"platform/business-intelligence":["trend","margin"],"platform/load-optimizer":["movement","margin"],"platform/route-optimizer":["movement","attention"],"platform/flolens":["attention","trend"],"platform/pin-protocol":["carrier","movement"],"platform/dealer-portal":["movement","message"],"solutions/brokers":["attention","margin"],"solutions/carriers":["movement","money"],"solutions/dealers":["movement","message"],"solutions/wholesale":["movement","attention"],"customers":["attention","movement"]
};
const panels:Record<string,()=>ReactNode>={attention:Attention,margin:Margin,movement:Movement,carrier:Carrier,ranking:Ranking,money:Money,message:Message,trend:Trend};
export function VisualExamples({slug}:{slug:string}){const pair=pairs[slug];if(!pair)return null;return <section className="pvl-wrap vx-section" aria-label="Workflow examples"><div className="vx-section-title"><div><p className="pvl-eyebrow">The details that move the work</p><h2>A closer look at the next step.</h2></div><p>Illustrative interfaces<br/>Sample data</p></div><div className="vx-grid">{pair.map(key=>{const Panel=panels[key];return <Panel key={key}/>})}</div></section>}
export {BotScenes as BotVisual} from "./BotScenes";
