import {RichContext} from "./RichContext";
import type {VisualKind} from "@/content/section-visuals";
const topics:Partial<Record<VisualKind,[string,string,string]>>={board:["Vehicle record","Pickup recorded","Delivery next"],portal:["Your customer’s vehicle","Movement status","Receiving details"],match:["Vehicle requirements","Carrier equipment","Lane experience"],capacity:["Vehicle dimensions","Deck configuration","Available position"],route:["Pickup location","Route context","Delivery window"],inspection:["Vehicle condition","Inspection evidence","Handoff record"],pin:["Requesting driver","Pickup location","Review authorization"]};
export function VisualContext({kind,active=0}:{kind:VisualKind;active?:number}){
if(kind==="match")return <div className="cx-special cx-shortlist"><div className="cx-special-heading"><span>CARRIER INTELLIGENCE</span><strong>A shortlist with a reason.</strong></div><div className="cx-match-lane"><span>DETROIT</span><b>→</b><span>NASHVILLE</span><small>3 vehicles · Open transport</small></div><div className="cx-candidates">{["Equipment fit","Lane history","Availability"].map((label,i)=><div className={active===i?"is-active":""} key={label}><span className="cx-monogram">{["A","B","C"][i]}</span><strong>Carrier {["A","B","C"][i]}</strong><div className="cx-fit-meter"><i style={{width:[92,76,58][i]+"%"}}/></div><small>{label}</small></div>)}</div><footer>ILLUSTRATIVE CANDIDATES · OPERATOR REVIEWS THE FIT</footer></div>;
if(kind==="portal")return <div className="cx-special cx-portal-preview"><div className="cx-portal-copy"><span>CUSTOMER WORKSPACE</span><strong>The movement,<br/>from their side.</strong><p>One shipment. A clear status. The details your customer needs.</p><div className="cx-portal-avatar">D<span>DEMO DEALERSHIP</span></div></div><div className="cx-phone"><div className="cx-phone-notch"/><small>MY SHIPMENT</small><strong>DEMO-1042</strong><span className="cx-phone-status">IN TRANSIT</span><div className="cx-phone-timeline">{["Pickup recorded","On the road","Delivery next"].map((label,i)=><div key={label} className={active===i?"is-active":""}><b>{i<2?"✓":"○"}</b><span>{label}</span></div>)}</div><footer>Detroit → Nashville</footer></div></div>;
if(kind==="pin")return <div className="cx-special cx-handoff"><div className="cx-special-heading"><span>PIN PROTOCOL / ILLUSTRATION</span><strong>A handoff with context.</strong></div><div className="cx-handoff-grid"><div className="cx-geofence"><div className="cx-radius"/><div className="cx-radius inner"/><div className="cx-location">⌖</div><span>Pickup location</span><b className="cx-driver-dot">D</b><small>Driver request</small></div><div className="cx-auth-card"><span>HANDOFF REVIEW</span><strong>DEMO-1042</strong>{["Driver identity","Location context","Release authorization"].map((label,i)=><div key={label} className={active===i?"is-active":""}><b>0{i+1}</b>{label}</div>)}<footer>Review before release →</footer></div></div></div>;
const labels=topics[kind];
const scenes:Record<string,[string,string,string]>={board:["transport","Illustration of vehicles beside a loaded auto transporter","One vehicle. A connected journey."],inspection:["inspection","Vehicle condition inspection with evidence markers and a camera","Condition. Evidence. Handoff."],capacity:["capacity","Separated transporter decks showing vehicle positions and an available slot","A place for every vehicle."],route:["route","Dealership locations connected by a highway and route waypoints","From pickup to delivery."]};
const scene=scenes[kind];
if(labels&&scene)return <div className={"cx-scene cx-"+kind}><img src={"/illustrations/"+scene[0]+"-context.webp"} alt={scene[1]} width="1536" height="1024" loading="lazy"/><div className="cx-scene-caption"><span>{kind==="board"?"THE MOVEMENT BEHIND THE RECORD":kind.toUpperCase()+" / VISUAL CONTEXT"}</span><strong>{scene[2]}</strong></div><div className="cx-hotspots" aria-hidden="true">{labels.map((s,i)=><div key={s} className={"cx-hotspot cx-point-"+i+(i===active?" is-active":"")}><b>{String(i+1).padStart(2,"0")}</b><span>{s}</span></div>)}</div><div className="cx-scene-footer"><span>DEMO-1042</span><span>Detroit <i>→</i> Nashville</span><span>ILLUSTRATION</span></div></div>;
if(kind==="documents"||kind==="ledger"||kind==="pricing")return <div className="cx-paper-scene"><div className={"cx-paper "+(active===0?"is-active":"")}><span>PREVAYL <b>DEMO-1042</b></span><strong>{kind==="documents"?"CARRIER FILE":"CUSTOMER INVOICE"}</strong><div className="cx-paper-lines"><i/><i/><i/></div><div className="cx-paper-total">{kind==="documents"?"Authority · Coverage":"$1,250"}<small>{kind==="documents"?"Review supporting records":"Customer obligation"}</small></div><div className="cx-paper-stamp">{kind==="documents"?"DOCUMENT REVIEW":"ACCOUNTS RECEIVABLE"}</div></div><div className="cx-paper-connector"><span>↔</span><small>Same order<br/>Separate records</small></div><div className={"cx-paper secondary "+(active===1?"is-active":"")}><span>PREVAYL <b>DEMO-1042</b></span><strong>{kind==="documents"?"SHIPMENT EVIDENCE":"CARRIER PAYABLE"}</strong><div className="cx-paper-lines"><i/><i/><i/></div><div className="cx-paper-total">{kind==="documents"?"eBOL · Handoff":"$950"}<small>{kind==="documents"?"Evidence with the movement":"Carrier obligation"}</small></div><div className="cx-paper-stamp">{kind==="documents"?"ORDER DOCUMENTS":"ACCOUNTS PAYABLE"}</div></div></div>;
if(kind==="trend"||kind==="forecast")return <div className="cx-analysis"><div><span>EXAMPLE / OPERATIONAL READ</span><strong>{kind==="forecast"?"Recorded → Projected":"Movement → Performance"}</strong><p>{kind==="forecast"?"Separate what happened from the outlook.":"Read the pattern, then inspect the loads."}</p></div><div className="cx-spark-chart" aria-hidden="true"><svg viewBox="0 0 280 100"><path d="M0 90H280M0 50H280M0 10H280" stroke="#2e4057" strokeWidth="1"/><path d="M4 80L45 61L83 69L123 35L162 44L205 22L270 10" stroke="#C9A84C" strokeWidth="3" fill="none"/>{[[4,80],[83,69],[162,44],[270,10]].map(([x,y])=><circle key={x} cx={x} cy={y} r="4" fill="#F0F4F8"/>)}</svg></div></div>;
return <RichContext kind={kind} active={active}/>;
}
