import type {Metadata} from "next";
import Link from "next/link";
import {PageHero} from "@/components/shared/PageHero";
import {CTA,Eyebrow,Steps} from "@/components/redesign/Shared";
const stages=[
 {title:"Intake",owner:"Order details",body:"Bring the customer, VIN, locations and timing into one record.",items:[["Verify the movement","Review the vehicle, lane and missing information before the next stage."],["Establish the position","Bring customer pricing and the carrier-cost target into the decision."]]},
 {title:"Market",owner:"Posting and offers",body:"Work the load within the pricing and escalation settings you configure.",items:[["Prepare the listing","Review the load details and the enabled marketplace integration."],["Evaluate the offer","Compare the proposed carrier rate with the position on the order."],["Escalate the exception","Put offers outside the configured limits in front of a person."]]},
 {title:"Booking",owner:"Carrier and documents",body:"Connect the carrier commitment with the order and its paperwork.",items:[["Confirm the carrier","Review the carrier record and the assignment details."],["Prepare the handoff","Keep the rate confirmation and driver details with the order."]]},
 {title:"Pickup & delivery",owner:"Milestones and exceptions",body:"Follow the movement and review the information needed at each handoff.",items:[["Review pickup","Check the driver, location and applicable authorization workflow."],["Track the milestones","Bring status events and documents back to the order."],["Handle the exception","Investigate missing information or a movement that needs attention."]]},
 {title:"Financial follow-through",owner:"Review the money",body:"Keep customer invoicing and carrier payment obligations visible after delivery.",items:[["Review the invoice","Check the customer charge and supporting delivery records."],["Review the carrier payable","Confirm the carrier’s terms and payment status separately from the customer’s payment."]]}
];
export const metadata:Metadata={title:"Dispatcher Bot — Follow the workflow",description:"Explore intake, market, booking, delivery and financial follow-through in Prevayl."};
export default function Page(){return <main className="pvl-redesign"><PageHero eyebrow="Platform / Dispatcher Bot" title="The work moves forward. You see the decisions." lead="Walk through the stages of dispatch automation. Review the settings, exceptions and handoffs that matter to your operation." primaryCta={{href:"#workflow",label:"Follow the workflow"}} secondaryCta={{href:"/contact?type=demo",label:"See a demo"}}/><section className="pvl-wrap pvl-section" id="workflow"><Eyebrow>From intake to follow-through</Eyebrow><h2>One order.<br/><em>A connected sequence.</em></h2><Steps items={stages.map(s=>s.title)}/><p className="pvl-section-lead">This walkthrough explains the workflow. Enabled integrations, permissions and automation settings determine which actions run in your organization.</p><div style={{marginTop:40}}>{stages.map((s,i)=><details key={s.title} className="pvl-workflow-stage" open={i===0}><summary><span className="pvl-workflow-number">{String(i+1).padStart(2,"0")}</span><span><strong>{s.title}</strong><small>{s.owner}</small></span><span className="pvl-workflow-plus" aria-hidden="true">+</span></summary><div className="pvl-workflow-body"><p>{s.body}</p><div className="pvl-feature-list">{s.items.map(([h,p])=><article key={h}><span className="pvl-feature-num" aria-hidden="true">→</span><div><h3>{h}</h3><p>{p}</p></div></article>)}</div></div></details>)}</div></section><section className="pvl-wrap pvl-section"><Eyebrow>Keep the controls close</Eyebrow><h2>Know what is enabled.<br/>Know what needs you.</h2><div className="pvl-control-strip"><div><span>Configure</span><strong>Stages and action modes</strong></div><div><span>Review</span><strong>Rates, limits and permissions</strong></div><div><span>Investigate</span><strong>Activity and exceptions</strong></div></div><Link className="pvl-text-link" style={{marginTop:25}} href="/platform/agents">Meet the individual bots →</Link></section><CTA/></main>}
