import type {Metadata} from "next";
import Link from "next/link";
import {CarrierScreens} from "@/components/redesign/CarrierScreens";
import "./carriers.css";
export const metadata:Metadata={title:"Trucking Companies — Run your fleet on Prevayl",description:"Auto transport TMS for load planning, drivers, ELD visibility, GM VTIMS and EDI, customer billing and driver settlements.",alternates:{canonical:"https://prevaylos.com/solutions/carriers/"}};
const demo="/contact?type=demo&role=carriers";
const stages=[{name:"Receive freight",id:"intake"},{name:"Build the load",id:"build"},{name:"Assign the team",id:"assign"},{name:"Follow the fleet",id:"track"},{name:"Record delivery",id:"deliver"},{name:"Review driver pay",id:"reconcile"}];
const sections=[
 {id:"section-0",number:"01",label:"Operations",title:"Put the office and fleet",gold:"on the same page.",body:"Direct customer work, brokered freight and recurring lanes all need the same discipline: a workable load, clear ownership and visibility into the movement.",cards:[{label:"PLAN",title:"Build around the work.",body:"Review vehicles, capacity and stop sequence in the load builder before assigning the movement.",link:"/platform/carriers?step=build#carrier-workflow",cta:"Explore load planning"},{label:"ASSIGN",title:"Give the team the context.",body:"Bring drivers, truck and trailer records, pickup requirements and delivery instructions into the operating process.",link:"/platform/carriers?step=assign#carrier-workflow",cta:"Explore the dispatch handoff"},{label:"CLOSE OUT",title:"Keep the delivery record.",body:"Review delivery status and available BOL, POD and supporting records before the work moves into financial review.",link:"/platform/carriers?step=deliver#carrier-workflow",cta:"Explore delivery records"}]},
 {id:"section-3",number:"03",label:"Financial control",title:"Know what to bill.",gold:"Know what to pay.",body:"Carry operational context into customer billing, company expenses and driver settlements. Keep the records behind the numbers available for review.",cards:[{label:"THE CUSTOMER SIDE",title:"Billing & receivables",body:"Prepare invoices and follow customer balances with the shipment records that support them.",link:"/platform/accounting",cta:"Explore accounting"},{label:"THE DRIVER SIDE",title:"Settlements & reconciliation",body:"Review load-level earnings, deductions and adjustments. Resolve differences before approved settlement and payroll steps.",link:"/platform/carriers?step=reconcile#carrier-workflow",cta:"Explore driver pay review"},{label:"THE COMPANY VIEW",title:"Expenses & financial review",body:"Review driver pay, fuel and equipment expenses alongside revenue to understand the costs behind your operation.",link:"/platform/business-intelligence",cta:"Explore reporting"}]}
];
function BusinessSection({index}:{index:number}){const s=sections[index];return <section id={s.id} className="pvl-wrap tc-section"><div className="tc-heading"><div><p className="pvl-eyebrow">{s.number} / {s.label}</p><h2>{s.title}<br/><em>{s.gold}</em></h2></div><p>{s.body}</p></div><div className="tc-pillars">{s.cards.map(c=><article key={c.title}><span>{c.label}</span><h3>{c.title}</h3><p>{c.body}</p><Link href={c.link}>{c.cta} ↗</Link></article>)}</div>{index===0?<div id="section-1" className="tc-map"><div className="tc-screen-intro"><h3>Your ELD connection.<br/>Your operations map.</h3><div><p>Supported ELD connections populate the fleet map with reported truck positions. Give operations managers the location context to follow the fleet, with timestamps that make stale reports visible.</p><Link className="pvl-text-link" href="/platform/carriers?step=track#carrier-workflow">Explore fleet visibility →</Link></div></div><CarrierScreens initial="map" fixed/><p className="tc-note">Provider permissions, reporting frequency and available data vary by connection. Review your ELD requirements during the demo.</p></div>:<CarrierScreens initial="settlements" fixed/>}</section>}
export default function Page(){return <main className="pvl-redesign tc-page"><section className="pvl-wrap tc-hero"><p className="pvl-eyebrow">For trucking companies / Auto transport TMS</p><h1>Your fleet moves vehicles.<br/><em>Prevayl runs the work.</em></h1><div className="tc-hero-bottom"><p>Bring your customers, dispatchers, drivers and financial records into one operating workflow. Plan the loads, follow the trucks and carry the work through to billing and driver pay.</p><div className="pvl-actions"><Link className="pvl-button" href={demo}>See how your fleet would run ↗</Link><Link className="pvl-text-link" href="/platform/carriers#carrier-workflow">Explore the product walkthrough →</Link></div></div><div className="tc-position"><span>YOUR CUSTOMERS</span><span>YOUR FLEET</span><span>YOUR OPERATING SYSTEM</span><p>The load board brings opportunities. The TMS runs the company behind them.</p></div></section>
<nav className="pvl-wrap tc-index" aria-label="Trucking company capabilities"><a href="#section-0"><span>01</span>Run the operation ↓</a><a href="#section-2"><span>02</span>Connect OEM freight ↓</a><a href="#section-3"><span>03</span>Control the money ↓</a></nav><BusinessSection index={0}/>
<section id="section-2" className="pvl-wrap tc-section"><div className="tc-heading"><div><p className="pvl-eyebrow">02 / OEM & enterprise freight</p><h2>Bring the connection<br/><em>into the operation.</em></h2></div><p>OEM freight should enter the same planning and dispatch process as the rest of your business. Review GM VTIMS and partner-specific EDI workflows alongside the team that will use them.</p></div><div className="tc-edi-flow" aria-label="EDI operating process"><div><span>RECEIVE</span><strong>Incoming tender</strong><p>Customer & movement details</p></div><b aria-hidden="true">→</b><div><span>MAP & REVIEW</span><strong>Order context</strong><p>Partner fields & requirements</p></div><b aria-hidden="true">→</b><div><span>OPERATE & RESPOND</span><strong>Shipment updates</strong><p>Configured status exchange</p></div></div><CarrierScreens initial="gm" fixed/><div className="tc-bottom-note"><p>Scope the transaction sets, partner mapping, credentials and acceptance testing for each connection. Availability depends on the partner and configured integration.</p><Link className="pvl-text-link" href="/platform/integrations/vtims-edi">Explore GM VTIMS & EDI →</Link></div></section><BusinessSection index={1}/>
<section id="section-4" className="pvl-wrap tc-section"><div className="tc-heading"><div><p className="pvl-eyebrow">See the product in context</p><h2>Follow one job.<br/><em>Explore the whole cycle.</em></h2></div><p>Start with the part of the operation you want to see. The walkthrough combines actual carrier screens with labeled workflow illustrations.</p></div><div className="tc-stage-links">{stages.map((s,i)=><Link key={s.id} href={"/platform/carriers?step="+s.id+"#carrier-workflow"}><span>0{i+1}</span><strong>{s.name}</strong><b>↗</b></Link>)}</div></section>
<section className="pvl-wrap tc-demo"><div><p className="pvl-eyebrow">A demo built around your trucking company</p><h2>Show us your operation.<br/><em>See how Prevayl fits.</em></h2><p>Walk through a lane, the people who move it and the records your office needs to close it out.</p><Link className="pvl-button" href={demo}>Plan your fleet demo ↗</Link></div><aside><h3>Bring the details that matter.</h3><ul>{["Fleet size and dispatch process","ELD provider and tracking needs","OEM or EDI partner requirements","Driver pay and accounting workflow"].map((t,i)=><li key={t}><span>0{i+1}</span>{t}</li>)}</ul></aside></section></main>}
